### ISSUE TITLE
Problem TURBO BOOST. TURBO BOOST is ON, but processor not support this

### ISSUE THREAD

**Issue by vincenzogianfelice** [cyring/CoreFreq#104]
Hi. when I type "./corefreq-cli -s" I see that the turbo boost feature is active ... but the processor doesn't support turbo boost. I have an Intel Core i3-6100 @ 3.70GHZ.
Output command "./corefreq-cli -s | grep -i turbo" is:

`|- Turbo Boost                                                          [UNLOCK]
   |- Turbo Activation                                                  [UNLOCK]
|- Turbo Boost                                                 TURBO       < ON>
`

**Comment by cyring** [comment]
Hi. Thanks for your report.
Indeed, I have also noticed that some architecture reports the wrong Turbo capability.
For example, my Xeon W3690 has a locked turbo but in fact it is the opposite.
My workaround will be to override the Turbo capability of your  `Core i3-6100` based on its CPU name.

1. can you print its full brand name, such as:
```
Intel(R) Xeon(R) CPU W3690 @ 3.47GHz
```
2. can you stress only one Core to show the frequency limit.
* press `[F3]` next choose `Turbo Select CPU...` then select CPU # 0
![2019-04-13-041629_804x644_scrot](https://user-images.githubusercontent.com/11563789/56073380-f6e81200-5da2-11e9-923f-6a2e7568e645.png)

**Comment by cyring** [comment]
This fix will query the TDP registers when Skylake is detected.
Remark: this a common code with Broadwell

1. Using the last version of _CoreFreq_, in the `corefreqk.c` file, replace the function `Query_Broadwell` with the code bellow:
https://github.com/cyring/CoreFreq/blob/68b559a28a4a1d4f9001afb768ac31bdd22bbcff/corefreqk.c#L2945
```C
void Query_Broadwell(void)
{
	Proc->Features.Uncore_Unlock = 1;
	Nehalem_Platform_Info();
	HyperThreading_Technology();
	Haswell_Uncore_Ratio(NULL);
	Intel_Turbo_TDP_Config();
	SandyBridge_PowerInterface();
}
```

2. Then rebuild `make clean all` and (re)start _CoreFreq_

3. Please post back the full output of `corefreq-cli -s`

CyrIng

**Comment by cyring** [comment]
My notes (from the Intel Software Developer’s Manual)
```
6th generation: Skylake microarchitecture
CPUID signatures: 06_4EH [Skylake_UY], 06_5EH [Skylake_S], and 06_55H [Skylake_X].

7th generation: Kaby Lake microarchitecture and 8th generation Coffee Lake microarchitecture
CPUID signatures: 06_8EH [Kabylake_UY], [Whiskey Lake] and 06_9EH [Kabylake].

Future Intel® Core™ processors: Cannon Lake microarchitecture
CPUID signature: 06_66H [Cannon Lake].

These processors support the MSR interfaces listed in :
Table 2-20
Table 2-21
Table 2-25
Table 2-29 : MSR_TURBO_ACTIVATION_RATIO, MSR_CONFIG_TDP_CONTROL, MSR_CONFIG_TDP_LEVEL2, MSR_CONFIG_TDP_LEVEL1, MSR_CONFIG_TDP_NOMINAL
Table 2-35
Table 2-39
Table 2-40
```

**Comment by cyring** [comment]
Fix released.
Can you please test and post back the full output of `corefreq-cli`

**Comment by vincenzogianfelice** [comment]
I updated...But core_freq still reports that the turbo boost is there:

`|- Turbo Boost                                                          [UNLOCK]
   |- Turbo Activation                                                  [UNLOCK]
|- Turbo Boost                                                 TURBO       < ON>`

![Screenshot 2019-04-14 16:50:40](https://user-images.githubusercontent.com/30395310/56093113-ce583900-5ec4-11e9-8d2e-e5952dd501b2.png)

**Comment by cyring** [comment]
Can you post the output of

1. `corefreq-cli -s`

2. screenshot of a single stressed CPU. For this, press F3, then Turbo and select CPU number 0.
Screenshots when the frequency is at its most value.

**Comment by cyring** [comment]
Fix released.
In the UI `IDA,TURBO` have to be OFF
Same in the `Technologies` window

**Comment by vincenzogianfelice** [comment]
Thank you. Now everything works correctly. The data is displayed correctly. For completeness, I post my output:

`|- Turbo Boost                                                          [UNLOCK]
   |- Turbo Activation                                                  [UNLOCK]
|- Turbo Boost                                                 TURBO       <OFF>`

Here is also the screenshot:

![Screenshot 2019-04-15 04:58:17](https://user-images.githubusercontent.com/30395310/56102092-9d125400-5f2a-11e9-9735-21297cde8bee.png)

...even if I didn't understand what "UNLOCK" means. What does it mean?

**Comment by cyring** [comment]
Great news that it works.  

`UNLOCK` is a bit status that the associated registers can be altered.
With your processor, `Turbo Activation` should have no effect.  

Verifying will be easier for me if you can post the full output of `corefreq-cli -s`

**Comment by vincenzogianfelice** [comment]
Sure, sorry:

`Processor                              [Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz]
|- Architecture                                                      [Skylake/S]
|- Vendor ID                                                      [GenuineIntel]
|- Microcode                                                        [       198]
|- Signature                                                            [ 06_5E]
|- Stepping                                                             [     3]
|- Online CPU                                                           [  4/4 ]
|- Base Clock                                                           [ 99.90]
|- Frequency            (MHz)                      Ratio                        
                 Min    799.17                    [   8 ]                       
                 Max   3696.18                    [  37 ]                       
|- Factory                                                              [100.00]
                       3700                       [  37 ]                       
|- Turbo Boost                                                          [UNLOCK]
                  1C   3696.18                    <  37 >                       
                  2C   3696.18                    <  37 >                       
                  3C   3696.18                    <  37 >                       
                  4C   3696.18                    <  37 >                       
|- Uncore                                                               [UNLOCK]
                 Min    799.17                    <   8 >                       
                 Max   3696.18                    <  37 >                       
|- TDP                                                            Level [  0:3 ]
   |- Programmable                                                      [UNLOCK]
   |- Configuration                                                     [  LOCK]
   |- Turbo Activation                                                  [UNLOCK]
             Nominal   3696.18                    [  37 ]                       
                                                                                
Instruction Set Extensions                                                      
|- 3DNow!/Ext [N,N]          ADX [Y]          AES [Y]  AVX/AVX2 [Y/Y] 
|- AVX-512      [N]  BMI1/BMI2 [Y/Y]        CLFSH [Y]        CMOV [Y] 
|- CMPXCH8      [Y]     CMPXCH16 [Y]         F16C [Y]         FPU [Y] 
|- FXSR         [Y]    LAHF/SAHF [Y]    MMX/Ext [Y/N]     MONITOR [Y] 
|- MOVBE        [Y]          MPX [Y]     PCLMULDQ [Y]      POPCNT [Y] 
|- RDRAND       [Y]       RDSEED [Y]       RDTSCP [Y]         SEP [Y] 
|- SGX          [Y]          SSE [Y]         SSE2 [Y]        SSE3 [Y] 
|- SSSE3        [Y]  SSE4.1/4A [Y/N]       SSE4.2 [Y]     SYSCALL [Y] 
                                                                                
Features                                                                        
|- 1 GB Pages Support                                      1GB-PAGES   [Present]
|- Advanced Configuration & Power Interface                     ACPI   [Present]
|- Advanced Programmable Interrupt Controller                   APIC   [Present]
|- Core Multi-Processing                                  CMP Legacy   [Missing]
|- L1 Data Cache Context ID                                  CNXT-ID   [Missing]
|- Direct Cache Access                                           DCA   [Missing]
|- Debugging Extension                                            DE   [Present]
|- Debug Store & Precise Event Based Sampling               DS, PEBS   [Present]
|- CPL Qualified Debug Store                                  DS-CPL   [Present]
|- 64-Bit Debug Store                                         DTES64   [Present]
|- Fast-String Operation                                Fast-Strings   [Present]
|- Fused Multiply Add                                       FMA|FMA4   [Present]
|- Hardware Lock Elision                                         HLE   [Missing]
|- Long Mode 64 bits                                         IA64|LM   [Present]
|- LightWeight Profiling                                         LWP   [Missing]
|- Machine-Check Architecture                                    MCA   [Present]
|- Model Specific Registers                                      MSR   [Present]
|- Memory Type Range Registers                                  MTRR   [Present]
|- OS-Enabled Ext. State Management                          OSXSAVE   [Present]
|- Physical Address Extension                                    PAE   [Present]
|- Page Attribute Table                                          PAT   [Present]
|- Pending Break Enable                                          PBE   [Present]
|- Process Context Identifiers                                  PCID   [Present]
|- Perfmon and Debug Capability                                 PDCM   [Present]
|- Page Global Enable                                            PGE   [Present]
|- Page Size Extension                                           PSE   [Present]
|- 36-bit Page Size Extension                                  PSE36   [Present]
|- Processor Serial Number                                       PSN   [Missing]
|- Restricted Transactional Memory                               RTM   [Missing]
|- Safer Mode Extensions                                         SMX   [Missing]
|- Self-Snoop                                                     SS   [Present]
|- Time Stamp Counter                                            TSC [Invariant]
|- Time Stamp Counter Deadline                          TSC-DEADLINE   [Present]
|- Virtual Mode Extension                                        VME   [Present]
|- Virtual Machine Extensions                                    VMX   [Present]
|- Extended xAPIC Support                                     x2APIC   [ x2APIC]
|- Execution Disable Bit Support                              XD-Bit   [Present]
|- XSAVE/XSTOR States                                          XSAVE   [Present]
|- xTPR Update Control                                          xTPR   [Present]
                                                                                
Technologies                                                                    
|- System Management Mode                                   SMM-Dual       [ ON]
|- Hyper-Threading                                               HTT       [ ON]
|- SpeedStep                                                    EIST       < ON>
|- Dynamic Acceleration                                          IDA       [OFF]
|- Turbo Boost                                                 TURBO       <OFF>
|- Virtualization                                                VMX       [ ON]
   |- I/O MMU                                                   VT-d       [ ON]
   |- Hypervisor                                                           [OFF]
                                                                                
Performance Monitoring                                                          
|- Version                                                        PM       [  4]
|- Counters:          General                   Fixed                           
|                     4 x 48 bits             3 x 48 bits                       
|- Enhanced Halt State                                           C1E       <OFF>
|- C1 Auto Demotion                                              C1A       < ON>
|- C3 Auto Demotion                                              C3A       < ON>
|- C1 UnDemotion                                                 C1U       < ON>
|- C3 UnDemotion                                                 C3U       < ON>
|- Frequency ID control                                          FID       [OFF]
|- Voltage ID control                                            VID       [OFF]
|- P-State Hardware Coordination Feedback                MPERF/APERF       [ ON]
|- Hardware-Controlled Performance States                        HWP       [ ON]
|- Hardware Duty Cycling                                         HDC       [ ON]
|- Package C-State                                                              
   |- Configuration Control                                   CONFIG   [   LOCK]
   |- Lowest C-State                                           LIMIT   [      8]
   |- I/O MWAIT Redirection                                  IOMWAIT   [Disable]
   |- Max C-State Inclusion                                    RANGE   [      8]
|- MWAIT States:    C0    C1    C2    C3    C4    C5    C6    C7                
|                    0     2     1     2     4     1     0     0                
|- Core Cycles                                                         [Present]
|- Instructions Retired                                                [Present]
|- Reference Cycles                                                    [Present]
|- Last Level Cache References                                         [Present]
|- Last Level Cache Misses                                             [Present]
|- Branch Instructions Retired                                         [Present]
|- Branch Mispredicts Retired                                          [Present]
                                                                                
Power & Thermal                                                                 
|- Clock Modulation                                             ODCM   <Disable>
   |- DutyCycle                                                        [  0.00%]
|- Power Management                                         PWR MGMT   [   LOCK]
   |- Energy Policy                                        Bias Hint   [      0]
|- Junction Temperature                                        TjMax   [  0:100]
|- Digital Thermal Sensor                                        DTS   [Present]
|- Power Limit Notification                                      PLN   [Present]
|- Package Thermal Management                                    PTM   [Present]
|- Thermal Monitor 1                                         TM1|TTP   [ Enable]
|- Thermal Monitor 2                                         TM2|HTC   [Present]
|- Units                                                                        
   |- Power                                               watt   [  0.125000000]
   |- Energy                                             joule   [  0.000061035]
   |- Window                                            second   [  0.000976562]`

**Comment by cyring** [comment]
Thanks for this output. 

Surprisingly, the Turbo Activation Nominal ratio of [  37 ] is provided by the register altb we know this processor does have any Turbo feature.

**Comment by cyring** [comment]
Last commit, you will get a fix for the Uncore lock state.
This should look this way (_depending on the current BCLK_):
```
|- Uncore                                                               [  LOCK]
                 Min    800.00                    [   8 ]                       
                 Max   3700.00                    [  37 ]
```

**Comment by cyring** [comment]
The remaining work is to determine which processors have a Uncore coefficient unlocked or not.

**Comment by vincenzogianfelice** [comment]
Good job.
Now I'd like to ask you a question. But what changes, as regards temperature control, between this tool and lm-sensors? I read around that lm-sensors can be dangerous ... so how does corefreq see temperatures? Is the operation like that of the lm-sensor tool? And how reliable is this measurement?

Thank you.

**Comment by cyring** [comment]
Thanks.
I **never** have an issue with lm-sensors. 
_CoreFreq_ is also using low level accesses to read the Processor digital sensors registers.
lm-sensors is however able to give much more information, especially chipsets voltage, fanspeed, etc. 
This of-course implies that the user has a good knowledge of her/his hardware.

_CoreFreq_ try to be as accurate as lm-sensors.

The true difficulties come from the lack of specifications supplied by Manufacturers to the open source projects.

**Comment by cyring** [comment]
I have rollback the Uncore Limit change which will now be applied only for IDA capable processors; starting from the Haswell architectures.

Please let me know if you still get the same result ?

**Comment by vincenzogianfelice** [comment]
Yes.
I saved the output of 'corefreq-cli -s' and saw the differences. Apparently nothing has changed. Also place a screenshots
![Screenshot 2019-04-19 19:56:55](https://user-images.githubusercontent.com/30395310/56436916-131d0f00-62cd-11e9-9559-54d93860232a.png)

**Comment by cyring** [comment]
Great, Thank you.
I believe we can close this topic.
