### ISSUE TITLE
CoreFreq and /proc/cpuinfo output different frequency information

### ISSUE THREAD

**Issue by BowenWang** [cyring/CoreFreq#116]
Hi,
I am using Intel i9 9900k in overclocking mode, after I install CoreFreq, I found that the frequency is different it outputs is different from /proc/cpuinfo.
The screenshots on my machine(these three pictures are shot at the same time):
![corefreq](https://user-images.githubusercontent.com/14265711/57962221-2c1fdc80-78da-11e9-8e40-8c14d297a262.png)
![cpuinfo](https://user-images.githubusercontent.com/14265711/57962223-30e49080-78da-11e9-8287-4570e571c059.png)
![lscpu](https://user-images.githubusercontent.com/14265711/57962225-36da7180-78da-11e9-9976-b97e2499545a.png)

Is there any problem? Which software should I trust?

**Comment by BowenWang** [comment]
I also found that the difference only occurs when there is no process running, if I try to run some stress test, then the frequency output will be the same(both are 4.7 GHz)

**Comment by BowenWang** [comment]
Screenshots of i7z and CoreFreq at the same time.
![i7z](https://user-images.githubusercontent.com/14265711/57962297-c849e380-78da-11e9-9e0d-c8f8b3606138.png)
![corefreq](https://user-images.githubusercontent.com/14265711/57962301-cc760100-78da-11e9-8127-acba8fa8eab3.png)

**Comment by cyring** [comment]
Indeed, they are the same but _CoreFreq_ shows the relative frequency which is based on the Processor performance counters sampling. In other terms, the frequency based on the usage.

Fyi, at a gigahertz speed, it's almost impossible to query the frequency in real time with an algorithm that will overflow the CPU. That's why manufacturers are providing the PMU to sample counters on a large scale.

At any time, with an idle processor, you can press the [p] key to display the Processor view in which you will find frequencies from the Minimum up to the Turbo.

Btw, your screenshot shows artifacts beside temperature: you have to disable the NMI watchdog

**Comment by BowenWang** [comment]
Ok, but what do you mean by 
> your screenshot shows artifacts beside temperature
?

**Comment by cyring** [comment]
The values in gray, at the right side of the Max temperature values. 
Looks like they are sliding out of their place.  
The same in the Averages, this 23% is unexpected.  
See this reference screen for example:  
![2019-05-19-172418_1024x644_scrot](https://user-images.githubusercontent.com/11563789/57984326-f81ff500-7a5a-11e9-8ff5-53272065c809.png)

**Comment by BowenWang** [comment]
Ok, this definitely seems weird, could it because of the NMI watchdog?

**Comment by cyring** [comment]
Yes if you don't have disable them (straight from the kernel boot command line)

**Comment by cyring** [comment]
Hello, 
If things are OK, and before closing the issue, [here](https://github.com/cyring/CoreFreq/wiki/CPU-support) is maintained a Hall of Fame: feel free to send me a Gist link with various CoreFreq Cli screenshots which I'll add under your Processor name.

**Comment by cyring** [comment]
Your 9900K is Thermal Velocity Boost capable, are you OK to test some code which will query the state of this technology ?

**Comment by cyring** [comment]
Closing the issue.
However let me know if your want to contribute to Thermal Velocity Boost at issue #121
