### ISSUE TITLE
How to get the values of TCC activation temperature(IA32_Temperature_Target - T_offset ) in Intel SandyBridge platform?

### ISSUE THREAD

**Issue by NRevathi** [cyring/CoreFreq#134]

**Comment by cyring** [comment]
Hello,
If you're asking for details, try the Client in json output. 

Please provide more information about what you can not get ?

**Comment by NRevathi** [comment]
./corefreq-cli -j
./corefreq-cli -s
gives the Target/Junction Temperature as 100C of the processor. I wanted to get the value of T_offset i.e. lower thermal threshold limit of the processor at which the Thermal Monitoring mechanism is triggered.
Thanks

**Comment by cyring** [comment]
Can you put a finger on the right MSR register ?
Those specs look like the closest subjects which feat your need:
* The TM2 Transition Target
* On of the Threshold Value fields
* Other ?

![2019-07-20-211254_1044x1391_scrot](https://user-images.githubusercontent.com/11563789/61583103-a1ef3100-ab33-11e9-9e0c-e7b3546921df.png)
![2019-07-20-210719_1044x1391_scrot](https://user-images.githubusercontent.com/11563789/61583104-a287c780-ab33-11e9-85f1-2fb4c729706f.png)
![2019-07-20-210610_1044x1391_scrot](https://user-images.githubusercontent.com/11563789/61583105-a287c780-ab33-11e9-968b-4ac5a05f9c1d.png)

**Comment by cyring** [comment]
Or is it this one you are interested in ?

https://github.com/cyring/CoreFreq/blob/ee915c4cb803208cf3326cfb1e8e0fa754ef391e/intelmsr.h#L883

From specs: 
> MSR_TEMPERATURE_TARGET (1A2H) Package
> TCC Activation Offset (R/W) [27:24]
> Specifies a temperature offset in degrees C from the temperature target (bits 23:16). PROCHOT# will assert at the offset target temperature. Write is permitted only if MSR_PLATFORM_INFO.[30] is set.

**Comment by cyring** [comment]
Postponed to the Roadmap #169
