### ISSUE TITLE
Haswell/Desktop - Energy Policy - Bias Hint

### ISSUE THREAD

**Issue by Waydjinn** [cyring/CoreFreq#143]
Bias Hint can be successfully changed on Haswell/Desktop, signature 06_3C in Experimental mode.

Please add it to the white-list.
![corefreq](https://user-images.githubusercontent.com/2992772/63786210-e8ce0480-c8f1-11e9-8abe-595392f84a3f.png)

**Comment by cyring** [comment]
Thanks for your report.

On Clock Modulation is also depending on the Experimental mode: can you  please test several ODCM percents with this Haswell processor ?  

Remarks:  
* You'll have to stress CPU to check if the frequency ratio is indeed limited by ODCM.  
* Tools menu provides CPU stressing functions.

Regards.

**Comment by Waydjinn** [comment]
ODCM is working fine.
See various DutyCycle stressed tests:
![CoreFreq_25percent](https://user-images.githubusercontent.com/2992772/63941519-248cd980-ca6c-11e9-8cb8-4ac4637a8d2b.png)
![CoreFreq_50percent](https://user-images.githubusercontent.com/2992772/63941535-28b8f700-ca6c-11e9-9987-6a7bca20460f.png)
![CoreFreq_75percent](https://user-images.githubusercontent.com/2992772/63941545-2bb3e780-ca6c-11e9-95f5-3ccddefcd79e.png)
![CoreFreq_ODCM_OFF](https://user-images.githubusercontent.com/2992772/63941557-2eaed800-ca6c-11e9-9873-3a17daac05ff.png)

**Comment by cyring** [comment]
Commit released.

**Comment by cyring** [comment]
Thanks for your star.  
Enjoy _CoreFreq_ and stay tuned, more to come...
