### ISSUE TITLE
CPU 9980xe support.

### ISSUE THREAD

**Issue by TDP-9000w** [cyring/CoreFreq#146]
I have a 9980xe and a 6850k that don't show the voltages on all cpus.
I saw another issue thread where some code changes were made to support.
What should I change to support these cpus?

Also, is there any way to make the corefreq cli run multi-instance?

**Comment by TDP-9000w** [comment]
`./corefreq-cli -s -m
Processor                            [Intel(R) Core(TM) i9-9980XE CPU @ 3.00GHz]
|- Architecture                                                      [Skylake/X]
|- Vendor ID                                                      [GenuineIntel]
|- Microcode                                                        [  33554526]
|- Signature                                                           [  06_55]
|- Stepping                                                            [      4]
|- Online CPU                                                          [ 18/ 18]
|- Base Clock                                                          [ 99.997]
|- Frequency            (MHz)                      Ratio                        
                 Min   1199.97                    [  12 ]                       
                 Max   2999.92                    [  30 ]                       
|- Factory                                                             [100.000]
                       3000                       [  30 ]                       
|- Performance                                                                  
   |- OSPM                                                                      
                 TGT   4199.89                    <  42 >                       
|- Turbo Boost                                                         [ UNLOCK]
                  1C   4199.89                    <  42 >                       
                  2C   4199.89                    <  42 >                       
                  3C   4199.89                    <  42 >                       
                  4C   4199.89                    <  42 >                       
                  5C   4199.89                    <  42 >                       
                  6C   4199.89                    <  42 >                       
                  7C   4199.89                    <  42 >                       
                  8C   4199.89                    <  42 >                       
                  9C    199.99                    <   2 >                       
                 10C    399.99                    <   4 >                       
                 11C    799.98                    <   8 >                       
                 12C   1199.97                    <  12 >                       
                 13C   1599.96                    <  16 >                       
                 14C   1799.95                    <  18 >                       
                 15C   2399.94                    <  24 >                       
                 16C   2799.93                    <  28 >                       
|- Uncore                                                              [ UNLOCK]
                 Min   2699.93                    <  27 >                       
                 Max   2699.93                    <  27 >                       
|- TDP                                                           Level [  0:2  ]
   |- Programmable                                                     [ UNLOCK]
   |- Configuration                                                    [   LOCK]
   |- Turbo Activation                                                 [ UNLOCK]
             Nominal   2999.92                    [  30 ]                       
              Level1   2099.94                    [  21 ]                       
              Level2   2099.94                    [  21 ]                       
                                                                                
Instruction Set Extensions                                                      
|- 3DNow!/Ext [N/N]          ADX [Y]          AES [Y]  AVX/AVX2 [Y/Y] 
|- AVX-512      [Y]  BMI1/BMI2 [Y/Y]      CLFLUSH [Y]        CMOV [Y] 
|- CMPXCHG8B    [Y]   CMPXCHG16B [Y]         F16C [Y]         FPU [Y] 
|- FXSR         [Y]    LAHF/SAHF [Y]    MMX/Ext [Y/N]  MONITOR/X[Y/N] 
|- MOVBE        [Y]          MPX [Y]    PCLMULQDQ [Y]      POPCNT [Y] 
|- RDRAND       [Y]       RDSEED [Y]       RDTSCP [Y]         SEP [Y] 
|- SGX          [N]          SSE [Y]         SSE2 [Y]        SSE3 [Y] 
|- SSSE3        [Y]  SSE4.1/4A [Y/N]       SSE4.2 [Y]     SYSCALL [Y] 
                                                                                
Features                                                                        
|- 1 GB Pages Support                                      1GB-PAGES   [Present]
|- Advanced Configuration & Power Interface                     ACPI   [Present]
|- Advanced Programmable Interrupt Controller                   APIC   [Present]
|- Core Multi-Processing                                  CMP Legacy   [Missing]
|- L1 Data Cache Context ID                                  CNXT-ID   [Missing]
|- Direct Cache Access                                           DCA   [Present]
|- Debugging Extension                                            DE   [Present]
|- Debug Store & Precise Event Based Sampling               DS, PEBS   [Present]
|- CPL Qualified Debug Store                                  DS-CPL   [Present]
|- 64-Bit Debug Store                                         DTES64   [Present]
|- Fast-String Operation                                Fast-Strings   [Present]
|- Fused Multiply Add                                       FMA|FMA4   [Present]
|- Hardware Lock Elision                                         HLE   [Present]
|- Long Mode 64 bits                                         IA64|LM   [Present]
|- LightWeight Profiling                                         LWP   [Missing]
|- Machine-Check Architecture                                    MCA   [Present]
|- Model Specific Registers                                      MSR   [Present]
|- Memory Type Range Registers                                  MTRR   [Present]
|- OS-Enabled Ext. State Management                          OSXSAVE   [Present]
|- Physical Address Extension                                    PAE   [Present]
|- Page Attribute Table                                          PAT   [Present]
|- Pending Break Enable                                          PBE   [Present]
|- Process Context Identifiers                                  PCID   [Present]
|- Perfmon and Debug Capability                                 PDCM   [Present]
|- Page Global Enable                                            PGE   [Present]
|- Page Size Extension                                           PSE   [Present]
|- 36-bit Page Size Extension                                  PSE36   [Present]
|- Processor Serial Number                                       PSN   [Missing]
|- Restricted Transactional Memory                               RTM   [Present]
|- Safer Mode Extensions                                         SMX   [Missing]
|- Self-Snoop                                                     SS   [Present]
|- Time Stamp Counter                                            TSC [Invariant]
|- Time Stamp Counter Deadline                          TSC-DEADLINE   [Present]
|- Virtual Mode Extension                                        VME   [Present]
|- Virtual Machine Extensions                                    VMX   [Present]
|- Extended xAPIC Support                                     x2APIC   [  xAPIC]
|- Execution Disable Bit Support                              XD-Bit   [Present]
|- XSAVE/XSTOR States                                          XSAVE   [Present]
|- xTPR Update Control                                          xTPR   [Present]
                                                                                
Technologies                                                                    
|- System Management Mode                                   SMM-Dual       [ ON]
|- Hyper-Threading                                               HTT       [OFF]
|- SpeedStep                                                    EIST       < ON>
|- Dynamic Acceleration                                          IDA       [ ON]
|- Turbo Boost                                                 TURBO       < ON>
|- Virtualization                                                VMX       [OFF]
   |- I/O MMU                                                   VT-d       [OFF]
   |- Hypervisor                                                           [OFF]
                                                                                
Performance Monitoring                                                          
|- Version                                                        PM       [  4]
|- Counters:          General                   Fixed                           
|                     8 x 48 bits             3 x 48 bits                       
|- Enhanced Halt State                                           C1E       <OFF>
|- C1 Auto Demotion                                              C1A       <OFF>
|- C3 Auto Demotion                                              C3A       <OFF>
|- C1 UnDemotion                                                 C1U       <OFF>
|- C3 UnDemotion                                                 C3U       <OFF>
|- Frequency ID control                                          FID       [OFF]
|- Voltage ID control                                            VID       [OFF]
|- P-State Hardware Coordination Feedback                MPERF/APERF       [ ON]
|- Hardware-Controlled Performance States                        HWP       [OFF]
|- Hardware Duty Cycling                                         HDC       [OFF]
|- Package C-State                                                              
   |- Configuration Control                                   CONFIG   [   LOCK]
   |- Lowest C-State                                           LIMIT   [      0]
   |- I/O MWAIT Redirection                                  IOMWAIT   [ Enable]
   |- Max C-State Inclusion                                    RANGE   [      3]
|- MONITOR/MWAIT                                                                
   |- State index:    #0    #1    #2    #3    #4    #5    #6    #7              
   |- Sub C-State:     0     2     0     2     0     0     0     0              
|- Core Cycles                                                         [Present]
|- Instructions Retired                                                [Present]
|- Reference Cycles                                                    [Present]
|- Last Level Cache References                                         [Present]
|- Last Level Cache Misses                                             [Present]
|- Branch Instructions Retired                                         [Present]
|- Branch Mispredicts Retired                                          [Present]
                                                                                
Power & Thermal                                                                 
|- Clock Modulation                                             ODCM   <Disable>
   |- DutyCycle                                                        [  0.00%]
|- Power Management                                         PWR MGMT   [   LOCK]
   |- Energy Policy                                        Bias Hint   <      6>
   |- Energy Policy                                          HWP EPP   [      0]
|- Junction Temperature                                        TjMax   [  0:110]
|- Digital Thermal Sensor                                        DTS   [Present]
|- Power Limit Notification                                      PLN   [Present]
|- Package Thermal Management                                    PTM   [Present]
|- Thermal Monitor 1                                             TM1   [ Enable]
|- Thermal Monitor 2                                             TM2   [Present]
|- Units                                                                        
   |- Power                                               watt   [  0.125000000]
   |- Energy                                             joule   [  0.000061035]
   |- Window                                            second   [  0.000976562]
CPU Pkg  Apic  Core Thread  Caches      (w)rite-Back (i)nclusive              
 #   ID   ID    ID     ID  L1-Inst Way  L1-Data Way      L2  Way      L3  Way 
000:BSP     0     0      0   32768  8     32768  8   1048576 16  25952256 11  
001:  0     2     1      0   32768  8     32768  8   1048576 16  25952256 11  
002:  0     4     2      0   32768  8     32768  8   1048576 16  25952256 11  
003:  0     6     3      0   32768  8     32768  8   1048576 16  25952256 11  
004:  0     8     4      0   32768  8     32768  8   1048576 16  25952256 11  
005:  0    16     8      0   32768  8     32768  8   1048576 16  25952256 11  
006:  0    18     9      0   32768  8     32768  8   1048576 16  25952256 11  
007:  0    20    10      0   32768  8     32768  8   1048576 16  25952256 11  
008:  0    22    11      0   32768  8     32768  8   1048576 16  25952256 11  
009:  0    32    16      0   32768  8     32768  8   1048576 16  25952256 11  
010:  0    34    17      0   32768  8     32768  8   1048576 16  25952256 11  
011:  0    36    18      0   32768  8     32768  8   1048576 16  25952256 11  
012:  0    38    19      0   32768  8     32768  8   1048576 16  25952256 11  
013:  0    40    20      0   32768  8     32768  8   1048576 16  25952256 11  
014:  0    48    24      0   32768  8     32768  8   1048576 16  25952256 11  
015:  0    50    25      0   32768  8     32768  8   1048576 16  25952256 11  
016:  0    52    26      0   32768  8     32768  8   1048576 16  25952256 11  
017:  0    54    27      0   32768  8     32768  8   1048576 16  25952256 11 `

**Comment by TDP-9000w** [comment]
Full load with Prime95    4.1ghz  Stable vcore 1.135 (bios)   180degF  NH-D15S air cooled. (ugh)
![4 1ghz](https://user-images.githubusercontent.com/56002331/65919640-34187e80-e39a-11e9-8be2-fd64c290c2b0.jpg)

**Comment by cyring** [comment]
Nice processor!

* For all CPU voltage, move this switch case...  

https://github.com/cyring/CoreFreq/blob/a8c5ef0c36c815d59fd009e7b79e85c8e4e39616/corefreq-cli.c#L8071

... just bellow...  

https://github.com/cyring/CoreFreq/blob/a8c5ef0c36c815d59fd009e7b79e85c8e4e39616/corefreq-cli.c#L8058

* About multi-client support : it will impact Daemon. What's your use case? 

* Skylake/X Uncore is not fully implemented b/c lack of hardware to work/test with. Same for IMC.

* Screenshots, I see wrong power measurements of 4W full Cores stressed. To debug

**Comment by TDP-9000w** [comment]
What's your use case?
Just local use...
I just want to run the regular corefreq-cli command in one terminal 
ALONG with a corefreq-cli -V in another terminal window.
When I do both, one of them stops.
Yea hardware should be cheaper!   Luck has it that I have access to this!
I can test stuff/screenshot/debug if you want to code for this platform.
Thanks, i will give the voltage fix a try.

**Comment by TDP-9000w** [comment]
Good,  it shows the voltages on all cores...  since i have all cores vlocked right now they are the same.
![9980xe-1 135v4 1ghz](https://user-images.githubusercontent.com/56002331/65934747-d43ec980-e3d3-11e9-831c-600b99e464c0.jpg)


Now I need to change the vcore to auto and watch the clocks, voltages, etc and write them down to get an idea of what each core can do.

**Comment by cyring** [comment]
* Fix released in latest version 1.66.5

* About 4.7 GHz, try one of my stress tools: go to `[F2] Menu > Tools` or shortcut `[O]`
`Conics` variants involve the FPU; others stress the ALU  
Press `[F10]` at any time to stop stressing loops.

**Comment by cyring** [comment]
Not sure if it is the right product [sheet] (https://ark.intel.com/content/www/us/en/ark/products/189126/intel-core-i9-9980xe-extreme-edition-processor-24-75m-cache-up-to-4-50-ghz.html), but I'm noticing some gaps:

* _CoreFreq_ got a TjMax of 110 whereas spec says 84°C
Please check if temperature in Celsius is right ?
* Turbo Boost or Turbo Max is version 3. 
In the Cli, do you read this version number beside TURBO in the "Technologies" window ?

I've noticed C-States are disabled in your BIOS. Could you activate them and check that they are well measured by _CoreFreq_
1. Core C-States
2. Package C-States 

Also can you enable in BIOS and verify the state of SpeedStep, HyperThreading and VT is well reported

About Power, this needs some debug code but we need a reference : not sure about a max of 165W

**Comment by cyring** [comment]
* On-Demand Clock Modulation 
Could you check if this legacy feature works with Skylake/X

1. Activate the `Experimental` Mode in Settings
![2019-10-01-160539_644x316_scrot](https://user-images.githubusercontent.com/11563789/65969891-14925c00-e455-11e9-946e-8d35da3069a7.png)
2. Enable `Clock Modulation`
![2019-10-01-160553_644x316_scrot](https://user-images.githubusercontent.com/11563789/65969940-2a078600-e455-11e9-8f66-1fc416c0b32b.png)
3. Once `ODCM` enabled, change the `DutyCycle` to 25%
![2019-10-01-160616_644x316_scrot](https://user-images.githubusercontent.com/11563789/65970004-47d4eb00-e455-11e9-97dd-0d93f5fb861c.png)
4. Starts a stress `Tool` on a selected CPU and check if the Core frequency is limited to 25% of its max
![2019-10-01-160724_644x316_scrot](https://user-images.githubusercontent.com/11563789/65970073-5de2ab80-e455-11e9-909c-478584694094.png)
5. Restore the CPU nominal frequency by deactivating `Clock Modulation`. Frequency should go back its top value.
![2019-10-01-160754_644x316_scrot](https://user-images.githubusercontent.com/11563789/65970225-a13d1a00-e455-11e9-8c3c-6e38081622cd.png)

* Remarks:
1. _this is an unstested feature with SKL/X, please save, sync your files before testing_
2. If test is OK, I will remove the Experimental requirement for SKL/X in next _CoreFreq_ release

Thank you

**Comment by cyring** [comment]
>  Some cores like to run 4.7ghz, and others hate it.

In [datasheet vol 1](https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/6th-gen-x-series-datasheet-vol-1.pdf)
1. Turbo Boost Max 3.0, one of the Core should be set in BIOS to realize the highest performance.
This CPU is the one to stress in the `Tools > Turbo Select CPU...`
2. With my Nehalem, Turbo Boost works only with SpeedStep enabled.  
The `Technologies window` can let you enable them at any time.
3. Overclock the One Core Ratio in `Turbo Boost` section, item `1C`
![2019-10-01-223219_644x420_scrot](https://user-images.githubusercontent.com/11563789/65998308-5b0aa980-e49b-11e9-8b59-bc414315ed44.png)


$ 5.2.5: The Target Ratio has to be set to the max value.
1. set the `Bias Hint` to the lowest energy policy in `Power & Thermal` window  
![2019-10-01-224202_644x420_scrot](https://user-images.githubusercontent.com/11563789/65998964-b9845780-e49c-11e9-901b-f83bd10e89f8.png)

2. in `Processor` window, the `OSPM TGT` can be set to a fixed ratio.  
  This requires however to let CoreFreq driver be registered as the OS CPU-Freq driver (thus blacklist any other drivers)
![2019-10-01-223037_644x420_scrot](https://user-images.githubusercontent.com/11563789/65998199-1da61c00-e49b-11e9-97b0-c150c2f775a4.png)

* In your previous output, HWP appears OFF.  
Not sure if the BIOS can present this feature. If feasible then:
1. enable HWP in `Performance` window  
2. set `HWP-EPP` to the lowest energy profile in `Power & Thermal` window  
3. set the `HWP TGT` Target and `HWP Max` Ratio to the highest value in `Processor` window.

* If the _CoreFreq_ kernel module is registered as the OS Idle driver then you can set one idle limit in the `Kernel data window` to reduce the C-State latency to C1 during the CPU stress.
![2019-10-01-222543_644x420_scrot](https://user-images.githubusercontent.com/11563789/65997900-8d67d700-e49a-11e9-96c6-cbe1ea8f92b8.png)

**Comment by cyring** [comment]
[Datasheet volume 2](https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/7th-gen-core-family-desktop-s-processor-lines-datasheet-vol-2.pdf) Table 2-3: does the `lspci -nn` command show the HOST and DRAM Controller Device ID `906E9` ?

**Comment by TDP-9000w** [comment]
Ok, lots of stuff to try.

The datasheets you linked are not the correct ones.

I found two datasheets here.
https://www.intel.com/content/www/us/en/products/processors/core/x-series/i9-9980xe.html#relatedresourcesblad

9980XE datasheet.
https://www.intel.com/content/www/us/en/products/processors/core/6th-gen-x-series-datasheet-vol-1.html

Spec update.
https://www.intel.com/content/www/us/en/products/docs/processors/core/6th-gen-x-series-spec-update.html

**Comment by TDP-9000w** [comment]
So, Running two instances of corefreq-cli would allow me to monitor all 3 things at once, 
core voltages, core temperatures, and core frequency.
Switching the window to see the voltages causes a delay, so screenshots of all 3 are not possible for analysis.

Or....  It would be useful for the voltage page to show core temps also.
![Fail-Pass](https://user-images.githubusercontent.com/56002331/66007212-bd998080-e46e-11e9-9b8d-c5f8d4dc01d1.jpg)
![Fail-Pass1](https://user-images.githubusercontent.com/56002331/66007217-bffbda80-e46e-11e9-9153-b98197e2819e.jpg)

Does your stress tools verify errors and stop only the core that failed?
I use prime95 because it only stops the core that fails the test, but keeps others going.
This allows one to determine the weakest cores versus the strongest in relation to initial thermal stress package hot spots.

**Comment by cyring** [comment]
> So, Running two instances of corefreq-cli would allow me to monitor all 3 things at once,
> core voltages, core temperatures, and core frequency.
> Switching the window to see the voltages causes a delay, so screenshots of all 3 are not possible for analysis.
> 
> Or.... It would be useful for the voltage page to show core temps also.

This is definitively an enhancement to add. In addition to Energy/Power counters per Core for capable Processors such as Zen. Planed for next days ...

> Does your stress tools verify errors and stop only the core that failed?
> I use prime95 because it only stops the core that fails the test, but keeps others going.
> This allows one to determine the weakest cores versus the strongest in relation to initial thermal stress package hot spots.

Nop, but it's a good use case to add.
So far, _CoreFreq_ can claim the OS to disable a Core : press shortcut `[#]` then select CPU
![2019-10-02-100049_644x316_scrot](https://user-images.githubusercontent.com/11563789/66027563-b31ccc80-e4ea-11e9-9190-da920ae73455.png)

**Comment by TDP-9000w** [comment]
So I  think my memory controller is NOT in the coretypes.h  you mentioned...
I saw numbers similar, but not exact.

Controller Device ID  of   :   0580      or   0880     or     8086,   
I don't know which one,   WTF is with intel and their datasheet not mentioning it.../ missing vol 2?
Not something we expect from such a company...  
 Whats next, intel cpus inside our crackerjack boxes?

 I would just add it to the list somewhere formatting the entry like the others, but I do not know if that is all that is needed, nor do I know which ID should be used from the output of lspci above, I hope i included the proper info from that output.

**Comment by cyring** [comment]
1. Location where you will store IDs for probing
https://github.com/cyring/CoreFreq/blob/734baac66a23bdfa4e7bb192f92119bca96db154/corefreqk.h#L1353

* This list contains device id to probe and the associated function which query registers
```c
static struct pci_device_id PCI_Skylake_X_ids[] = {
	{
	PCI_DEVICE(PCI_VENDOR_ID_INTEL, 0x1234),
		.driver_data = (kernel_ulong_t) SKL_IMC
	},
	{0, }
};
```
* you just have to replace `0x1234` with the IMC id. Datasheet mentions it HA or SA Agent
I would start with `0x2066` from your lspci output
* _list must be terminated by `{0, }`_

2. Rebuild and test
* if lucky `SKL_IMC` function may decode bits
  _if your IMC platform works the same as Skylake/Desktop_
* High chance of CPU crash, save your files.

**Comment by cyring** [comment]
3. Next add a case switch in the Daemon bellow this stattement
https://github.com/cyring/CoreFreq/blob/734baac66a23bdfa4e7bb192f92119bca96db154/corefreqd.c#L2805
```c
	case 0x1234:	/* Skylake/X */
		SKL_CAP(Shm, Proc, Core);
		SKL_IMC(Shm, Proc);
		SET_CHIPSET(IC_SUNRISEPOINT);
		break;
```
* replace `0x1234` with the working IMC id you found

**Comment by TDP-9000w** [comment]
I tried 0x2066 for both.
The daemon, and cli both start, but the client does nothing when selecting the memory controller menu.   No errors under syslog, just statement of 
kernel: corefreq: unload 
kernel: corefreq: (6:-1): Processor [ 06_55] Architecture [Skylake/X] CPU [18/18]

**Comment by cyring** [comment]
Thank you for trying.  
It means that all IDs tested have been probed, execution had followed the expected code path where bus speed is hard corded. Unfortunately registers failed to be queried. So we need find a specification of the architecture to decode the right registers. Especially the MCHBAR and the relative offsets where to query the IMC registers, plus the layout of their bits.

**Comment by TDP-9000w** [comment]
Only thing i can see related is https://www.intel.com/content/dam/www/public/us/en/documents/manuals/6th-gen-core-family-uncore-performance-monitoring-manual.pdf
Page 17
```
3.3
IMC Events
The integrated memory controller un
it of the 6th Generation Intel
®
 Processor contains 
five model specific, fixed counters that allow for monitoring the number of requests to 
DRAM.
The fixed counters residing in the memory controller monitor transaction requests 
coming from various sources, e.g. the processor cores, the graphic engine, or other I/O 
agents. Unlike the MSR based performance counter registers in the CBo and ARB, the 
IMC fixed counter interface uses memory-ma
pped I/O reads from physical memory at 
the offsets specified in the IMC event table.
This set of counters are free-running and always-running. Software can read the value, 
wait for a desired internal, read again, then
 subtract the first sample from the second 
to determine how many times the event 
incremented in the sample interval.
The IMC counters below are model specific, meaning they may change or not be 
supported in the future.
To obtain the BAR address, read the value (in PCI configuration space) at Bus 0; Device 
0; Function 0; Offset 48H and mask with the value 0x0007FFFFF8000.
§
Table 3-3.
IMC Counters
Name
Address
Description
DRAM_GT_REQUESTS
BAR+0x5040
Counts every read/write
 request entering the Memory Controller 
to DRAM (sum of all channels) from the GT engine. Each partial 
write request counts as a request incrementing this counter. 
However same-cache-line partial wr
ite requests are combined to 
a single 64-byte data transfers from DRAM. Therefore 
multiplying the number of reques
ts by 64-bytes will lead to 
inaccurate GT memory bandwidth. The inaccuracy is proportional 
to the number of same-cache-
line partial writes combined.
DRAM_IA_REQUESTS
BAR+0x5044
Counts every read/w
rite request (demand and HW prefetch) 
entering the Memory Controller to DRAM (sum of all channels) 
from IA. Each partial write request counts as a request 
incrementing this counter. However same-cache-line partial write 
requests are combined to a sing
le 64-byte data transfers from 
DRAM. Therefore multiplying th
e number of requests by 64-
bytes will lead to inaccurate
 IA memory bandwidth. The 
inaccuracy is proportional to the number of same-cache-line 
partial writes combined.
DRAM_IO_REQUESTS
BAR+0x5048
Counts 
every read/write request entering the Memory Controller 
to DRAM (sum of all channels) from all IO sources (e.g. PCIe, 
Display Engine, USB audio, etc.). Each partial write request 
counts as a request incrementing this counter. However same-
cache-line partial write requests
 are combined to a single 64-
byte data transfers from DR
AM. Therefore mu
ltiplying the 
number of requests by 64-bytes will lead to inaccurate IO 
memory bandwidth. The inaccuracy is proportional to the 
number of same-cache-line partial writes combined.
DRAM_DATA_READS
BAR+0x5050
Counts every read (R
dCAS) issued by the 
Memory Controller to 
DRAM (sum of all channels). All 
requests result in 64-byte data 
transfers from DRAM. Use for accurate memory bandwidth 
calculations.
DRAM_DATA_WRITES
BAR+0x5054
Counts every write (WrC
AS) issued by the Memory Controller to 
DRAM (sum of all channels). All 
requests result in 64-byte data 
transfers from DRAM. Use for accurate memory bandwidth 
calculations
```

**Comment by cyring** [comment]
Does lspci give an ID facing BDF 0:0:0 ?

**Comment by cyring** [comment]
Kernel got something:
https://github.com/torvalds/linux/blob/0f1a7b3fac0583083ca19d4de47403511ced3521/drivers/edac/skx_base.c#L65

**Comment by TDP-9000w** [comment]
You mean this ?
```
lspci
00:00.0 Host bridge [0600]: Intel Corporation Sky Lake-E DMI3 Registers [8086:2020] (rev 04)
```

**Comment by cyring** [comment]
That's enough IDs and I bet this edac driver is running in your system ?
Enabling the kernel debug level should reveal its `edac_dbg` traces, and let us read the IMC properties.
Clearly this driver code shows registers and decoding protocol I never work with; and I wonder where those specs are coming from...

**Comment by TDP-9000w** [comment]
I tried turning on kernel debug but was confused at what string i should use.
Too many options...
```
        acpi.debug_layer=       [HW,ACPI,ACPI_DEBUG]
        acpi.debug_level=       [HW,ACPI,ACPI_DEBUG]
                        Format: <int>
                        CONFIG_ACPI_DEBUG must be enabled to produce any ACPI
                        debug output.  Bits in debug_layer correspond to a
                        _COMPONENT in an ACPI source file, e.g.,
                            #define _COMPONENT ACPI_PCI_COMPONENT
                        Bits in debug_level correspond to a level in
                        ACPI_DEBUG_PRINT statements, e.g.,
                            ACPI_DEBUG_PRINT((ACPI_DB_INFO, ...
                        The debug_level mask defaults to "info".  See
                        Documentation/acpi/debug.txt for more information about
                        debug layers and levels.

                        Enable processor driver info messages:
                            acpi.debug_layer=0x20000000
                        Enable PCI/PCI interrupt routing info messages:
                            acpi.debug_layer=0x400000
                        Enable AML "Debug" output, i.e., stores to the Debug
                        object while interpreting AML:
                            acpi.debug_layer=0xffffffff acpi.debug_level=0x2
                        Enable all messages related to ACPI hardware:
                            acpi.debug_layer=0x2 acpi.debug_level=0xffffffff

                        Some values produce so much output that the system is
                        unusable.  The "log_buf_len" parameter may be useful
                        if you need to capture more output.
```
https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html

I'll give these a try.
```
                        Enable all messages related to ACPI hardware:
                            acpi.debug_layer=0x2 acpi.debug_level=0xffffffff

                        Some values produce so much output that the system is
                        unusable.  The "log_buf_len" parameter may be useful
                        if you need to capture more output.
```

**Comment by cyring** [comment]
`skx_edac` is the driver to track.  
Do a `lsmod` first to check if it is running or not in your system.  

In its source code, the `edac_dbg` prints are source of interest, such as DIMM geometry (here)[https://elixir.bootlin.com/linux/latest/source/drivers/edac/skx_base.c#L526] 

In code, most traces seem at debug level 2; you can change level just for the time of restarting this driver, to find them among the last lines of kernel log. 
```
modprobe -r skx_edac ; modprobe skx_edac
```

**Comment by TDP-9000w** [comment]
my lsmod lists nothing about skx_edac

**Comment by cyring** [comment]
Hello,

Version 1.67, per Core Temperature and RAPL counters added to the view `Power & Voltage`

Thanks for your tests

Regards

**Comment by TDP-9000w** [comment]
Ok, will get to those tests asap, thanks for the change works great.

So it turns out my logs show this:
```EDAC sbridge: Failed to register device with error -19.
EDAC sbridge: Couldn't find mci handler
EDAC sbridge: CPU SrcID #0, Ha #0, Channel #0 has DIMMs, but ECC is disabled
```

**Comment by cyring** [comment]
Thanks.

So one EDAC static driver may run, not a module. I believe, the log can be dynamically increased to get further details.

I'm still refactoring the Voltage output which is now a 3^2 dimension (Voltage, Temp, Power), each matrix cell of 4 case values (None, Per SMT, Per Core, Per Package). Maths and code optimizations are still in progress.
I've released the intermediate version 1.67.4 which should conditionally display or not the relevant information depending on hardware. Feel free to post your View to let me evaluate any issues.

**Comment by cyring** [comment]
Refactoring of the view is completed in the latest version. Thank you for your returns.

**Comment by cyring** [comment]
Hello,
Did you have a chance to test the new Voltage view ? What about the per Core results facing total power ?  
Do you also have results from previous requests, starting from ODCM ?
Thanks
