### ISSUE TITLE
Visualiser des enregistrements Ascii

### ISSUE THREAD

**Issue by kaystream** [cyring/CoreFreq#168]
Pour visionner les enregistrements réalisés par CoreFreq, les commandes ci-dessus sont possibles : 
En perl :
`perl -pe "system 'sleep 0.5'" /opt/CoreFreq.1582892671/corefreq_e9b7e5dd7531.asc`
En awk:
`awk '{print $0; system("sleep 0.5");}' /opt/CoreFreq.1582892671/corefreq_e9b7e5dd7531.asc`

**Comment by cyring** [comment]
Excellent, merci l'ami :+1: 

Peut-on faire disparaître le curseur, le temps de la visualisation ?

**Comment by cyring** [comment]
Salut, la version Master est livrée et à jour.  
As tu réussi à basculer le mode Turbo Boost ?

N'oublie pas les pré-requis d'un processeur Intel:
* capable IDA
* SpeedStep EIST activé
* C-States activés, à minima le niveau C3 qui doit réaliser un Idle via le couple d'instructions MONITOR / MWAIT (par default le Kernel ou `corefreqk.ko Register_Idle=1`
* Coefficient multiplicateur du P-State Target correctement réglé  pour tous les cœurs: 
- Nehalem, Westmere, le ratio Target doit être égal au max ratio, non Turbo, plus 1
- SandyBridge et architectures suivantes: le ratio Target doit être strictement supérieur, jusqu'au plus haut coefficient Turbo, single Core

* Lorsque tous ces pré-requis sont réalisés alors le Turbo mode peut être activé

Son fonctionnement se mesurant au travers d'un single Core stress. cf. Outils-Stress-CPU

**Comment by cyring** [comment]
N'hesites pas à revenir par ici quand tu auras des réponses.
