### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cyring** [cyring/CoreFreq#169]
# EDIT: Jul. 29, 2021
----
## Tools
* AVX stress loops per CPU
* Idle loops if Processor is user mwait capable

## Build
* User defined Makefile argument : `CORE_COUNT` 
  To scale _CoreFreq_ up to 8 x sockets x 64 Cores x 2 threads = 1024 CPUs **[done]**  

* `man` manuel
  Is it possible to embed a colorful ASCII screenshot of `corefreq-cli` into the man source file ?  

* `make menuconfig`
  A simple shell UI, with the help of the common ANSI escape sequences. _Especially no other UI dependencies that could break the CoreFreq build_. 
  
* How to [Sign](https://wiki.archlinux.org/index.php/Signed_kernel_modules) the _CoreFreq_ kernel module for [Secure Boot](https://ubuntu.com/blog/how-to-sign-things-for-secure-boot) **[contribution is welcomed]**

* To refactor the _CoreFreq_ ISO image (since it is broken with latest [`Archiso`](https://wiki.archlinux.org/title/archiso)).  **[done]**
  Buildroot is also a work in progress for a smaller size media.

## Architecture
* Zhaoxin KaiXian KX-U6780A CPUID signature `07_3Bh Stepping 1` **[testers needed]**  

* [coreboot](https://doc.coreboot.org/soc/amd/family17h.html) SOC 
* AMD EPYC & Threadripper : 
  To provide the Temperature, Voltage, Power sensors per CCD and per Socket **[testers needed]**
   1. Castle Peak **[done]**
   2. EPYC/Naples/Rome  **[testers needed]**
* Refactor the topology to include cluster identifiers (AMD CCD, AMD CCX, Intel cluster) **[done]**

* All MP architectures: Design one service processor per Socket 
  (incl. Topology, Features and technologies, Hot-plugging, Stress tools, ...) 

* Decode the remaining memory controllers **[WiP]** **[testers needed]** 
* Scale the IMC decoders up to 8-12 channels 
* Probably, decode the DIMM SPD timings. _The base of ICs is quiet large: discouraging!_  

* Add Super-I/O registers for Voltage and Fans; when datasheets are available **[WiP]**  

* [AMD/Zen3] Implement the Host System Management Port (HSMP) interface  and its mailbox SMU protocol.
  As specified in [`PPR Vol 2 for AMD Family 19h Model 01h B1`](https://www.amd.com/system/files/TechDocs/55898_pub.zip) volume 2  **[done 3950X]**

### CLI 
* Pop-up a driver message box when clearing event bits from `HOT` window is not safe; and thus rejected by driver. See issue #225

* A view or a window to dump some common MSR, and PCI space registers. 
  _Allow User to define addresses to be queried_  

* Catch the Mouse events translated in ANSI codes  

* Filter the Cli outputs based on the sensors scope. **[done]**  

* Send escape sequences to save, modify and restore the RGB pallet  **[done]**  

* Add a new argument for the number of print iterations. #223 **[done]**  

### GUI 
* GUI is now moved to its own [repository](https://github.com/cyring/CoreFreq.gui)  **[postponed]**

## Algorithms
* Governor: best core; big little core; power/thermal core; cluster awareness **[Hybrid processor needed]**

* Synchronization of the monitoring loops in kernel module with the backend threads in the user-space Daemon: 
  Find a way to relinquish the waiting time to the kernel & `Timer-Thread` synchronization rather than passive loop.  

* Create sort of RCU, shared by Driver and Daemon, to transfer the full Tasks list.  
  Tasks are currently limited to a SHM dimension. Number of tasks is undefined and thus a limit is applied.  
  Enhancement could be a ring buffer between Driver and Daemon to dump and flush the task RCU when retrieved.  
  Another ring would be also needed between Daemon and Client.  
  The CPU overhead claimed by those ring operations, compared to a SHM implementation, is in question.  

* A set of getters/setters to the SHM data 
  Uniformed API at the disposal of the Cli and the GUI **[postponed]**

**Comment by gdiazlo** [comment]
Thanks for this great tool! 

I guess you already give it a though, but, Is it too complicated to support the sensors interface? that way other tools can handle the UI (ksysguard, gnome monitor, etc.)

Again, thanks!

**Comment by cyring** [comment]
> Thanks for this great tool!

Thank you for using _CoreFreq_

> 
> I guess you already give it a though, but, Is it too complicated to support the sensors interface? that way other tools can handle the UI (ksysguard, gnome monitor, etc.)
> 
> Again, thanks!

Not so complicated when looking at (coretemp)[https://elixir.bootlin.com/linux/latest/source/drivers/hwmon/coretemp.c] as an example. 
_CoreFreq_ is, so far, covering much less sensors than the available lm_sensors drivers ...

**Comment by cyring** [comment]
## Power limits 
( if registers available ) : https://github.com/cyring/CoreFreq/issues/60#issuecomment-517957899
Intel: TVB, PL1, PL2, TAU
AMD Zen: PPT, TDC, EDC

## Thermal Velocity Boost
 https://github.com/cyring/CoreFreq/issues/60#issuecomment-449668251
[Thermal Velocity Boost](https://en.wikichip.org/wiki/intel/thermal_velocity_boost)
Maximus X/XI & Strix Motherboards (Z370/Z390) > [MCE explanations and others](https://rog.asus.com/forum/showthread.php?106375-MCE-explanations-and-others)
> MSR 0x150 ... set bit 63 to 1 and [39:32] to 18h
> Bit 3 shows you if TVB is enabled or disabled (0=disabled).

## Some Registers
Raised in issue #60

**Comment by cyring** [comment]
# Refactoring the `Topology` window to display the AMD Zen CCD

* _The tests bellow are also including a disabled CPU_
![CoreFreq_Topology_AMD_Zen](https://user-images.githubusercontent.com/11563789/92123384-19d9f280-edec-11ea-87a2-773b12810b3c.png)
* Intel non regression
![CoreFreq_Topology_Intel](https://user-images.githubusercontent.com/11563789/92123417-278f7800-edec-11ea-8863-ab21ee610939.png)

**Comment by cyring** [comment]
# AMD APM Master Mode
* [what-does-amd-application-power](https://www.ronwoods.us/2014/02/what-does-amd-application-power.html)
* coreboot/latest/source/src/vendorcode/amd/agesa/f16kb/Proc/CPU/Family/0x16/KB/F16KbPowerMgmt.h
```
/* Core Performance Boost Control Register D18F4x15C */

/// Core Performance Boost Control Register
typedef struct {
  UINT32 BoostSrc:2;                 ///< Boost source
  UINT32 NumBoostStates:3;           ///< Number of boosted states
  UINT32 :2;                         ///< Reserved
  UINT32 ApmMasterEn:1;              ///< APM master enable
  UINT32 CstatePowerEn:1;            ///< C-state Power Enable
  UINT32 :22;                        ///< Reserved
  UINT32 BoostLock:1;                ///<
} CPB_CTRL_REGISTER;
```
* AMD Ryzen 9 3950X 16-Core Processor
```
zencli pci bus:0x0-dev:0x18-fn:0x4-reg:0x15c
[0x8000c45c] READ(pci) = 0x001b0189 (1769865)
   60   56   52   48   44   40   36   32   28   24   20   16   12   08   04   00
 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0001 1011 0000 0001 1000 1001
```
