### ISSUE TITLE
Ubuntu 14.04 segmentation fault

### ISSUE THREAD

**Issue by jesusgn90** [cyring/CoreFreq#18]
Hi man, this software is amazing, but when i start the client, i two or three seconds it give me a segmentation fault. 

Environment:
`Ubuntu 14.04`
`64 bits`
`Intel Core 2 duo`
`4GB RAM`

Here is a screenshot:

![segmentation](https://cloud.githubusercontent.com/assets/8860227/23021959/e36061b6-f44e-11e6-88f9-337c8e6fd06a.png)

**Comment by cyring** [comment]
This is due to counters conflict with nmi_watchdog.
In your kernel, disable it. For example: nmi_watchdog=0
See the FAQ for instructions.

**Comment by jesusgn90** [comment]
Ok thanks
