### ISSUE TITLE
[AMD][Family 17h][Zen] IOMMU Enablement State

### ISSUE THREAD

**Issue by cyring** [cyring/CoreFreq#193]
# _CoreFreq_ version [`1.79.5`]
## Git branch availability [`master`]
* MATISSE and APU of models 20h can now be queried for their IOMMU state
![CoreFreq_AMD_Zen_IOMMU](https://user-images.githubusercontent.com/11563789/86240112-18900d80-bb90-11ea-8173-fbe11f12e314.png)
* The same option found in BIOS at:
![200701133551](https://user-images.githubusercontent.com/11563789/86240351-9bb16380-bb90-11ea-876c-710ee8a7da36.png)

* **Contribution**: 
If you want to get yours, please post your `lspci -nn` output regarding the IOMMU device

**Comment by olejon** [comment]
Yes. Don't know where you found that option, since you searched in UEFI. But on my Motherboard it's called `SR-IOV` and it's the only Setting under some Section in Advanced. A drop-down.

`00:00.2 IOMMU [0806]: Advanced Micro Devices, Inc. [AMD] Device [1022:1481]`

![Screenshot_20200701-160917__01](https://user-images.githubusercontent.com/2082551/86260719-eeeddb00-bbbd-11ea-8d5f-401675231930.jpg)

**Comment by cyring** [comment]
Thanks for your test but if the device shows up in `lspci` then it has to be enabled or auto in BIOS.
Meanwhile I will check my BIOS if `SR-IOV` and  `IOMMU` are or not separated options ?

**Comment by olejon** [comment]
It's enabled. Only other option is disabled (no Auto). I've been through ALL Settings 100 times and NOWHERE have I've seen IOMMU...  As I understand it it's the same as `VT-d` on Intel (a website said so).

I can try searching...

I read this: https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.0/html/hardware_considerations_for_implementing_sr-iov/index

**Comment by olejon** [comment]
**Found it!**

* It's under
  * `Advanved > AMD CBS`
* Not that it changed *anything*. Seems like `Auto` was enough to enable it, with `SR-IOV = Enabled`
* Pretty darn sure `Technologies` before said `I/O MMU = [OFF]`

```
# lspci -nn
00:00.2 IOMMU [0806]: Advanced Micro Devices, Inc. [AMD] Device [1022:1481]
```

![IOMMU](https://user-images.githubusercontent.com/2082551/86287709-eeb70500-bbe8-11ea-8636-415fa9f7f497.png)

**Comment by cyring** [comment]
Thanks for your efforts. 

So do you mean you get a match between the BIOS state and the _CoreFreq_ state ?

IOMMU disabled in both ?
IOMMU enabled in both ?

**Comment by olejon** [comment]
* First has `SR-IOV = Enabled` only and was then `IOMMU = Auto` before I found it (seems enough to enable SR-IOV only)
* Second has `Both = Enabled` (not that it does anything it seems)

Default is `SR-IOV = Disabled` and `IOMMU = Auto`. Which seems to disable AMD-V.

**Comment by cyring** [comment]
IOMMU state confirmed with Ryzen 2700X
https://github.com/cyring/CoreFreq/issues/54#issuecomment-652788534

**Comment by olejon** [comment]
You got it right? Just `SR-IOV = Enabled` and let `IOMMU = Auto` and it enables it, according to `lspci -nn` and `CoreFreq > Technologies`. I guess you can reproduce that. You have ASUS too.
