### ISSUE TITLE
 corefreqd.service should use proper path for corefreqd 

### ISSUE THREAD

**Issue by bubbleguuum** [cyring/CoreFreq#197]
By default, corefreqd is installed in /usr/bin so it makes sense to have  corefreqd.service use /usr/bin/corefreqd instead /usr/bin/corefreqd. It could also use the value of PREFIX in Makefile to dynamically modify corefreqd.service  at install time to use the proper path

**Comment by cyring** [comment]
Hello,

_Sorry for being long to provide a fix._

To my surprise, `ExecStart` can work without an absolute path to `corefreqd`

For your tests, you can try the `develop` branch

ArchLinux Users can also test this branch by changing the `source` line in the `PKGBUILD`
```
source=(git+${url}.git#branch=develop)
```

**Comment by cyring** [comment]
Hello,

I'm tagging [1.80-rc.1](https://github.com/cyring/CoreFreq/tree/1.80-rc.1) as ready for packaging

**Comment by cyring** [comment]
Change had been provided.
Regards
CyrIng
