### ISSUE TITLE
[AMD/Family 17h] Memory Controller

### ISSUE THREAD

**Issue by cyring** [cyring/CoreFreq#212]
* Guessing the DIMM Single/Dual ranks

1. Single Rank
Zen2 / 3800X + Crucial Ballistix `BLM16G40C18U4B.M8FB1`
![CoreFreq_Ryzen_Single_Rank](https://user-images.githubusercontent.com/11563789/98918987-9533e080-24ce-11eb-922d-275ed54bda0c.jpeg)

2. Dual Ranks
Zen2 / 3950X + G.Skill Trident Z `F4-3600C16-16GTZN`
![CoreFreq_Ryzen_Dual_Ranks](https://user-images.githubusercontent.com/11563789/98914890-7f6fec80-24c9-11eb-935d-b1c907aaa95a.jpeg)
* This code is available in the `develop` branch, **your tests are welcomed**.

**Comment by adatum** [comment]
Dual Rank
Zen+ / 2700X + G.SKILL TridentZ F4-3200C14D-32GTZ

![rank](https://user-images.githubusercontent.com/9773655/98969513-e9de5800-24dc-11eb-9e58-eba061b9fd14.png)
