### ISSUE TITLE
DTS shown on Ryzen 5800X (and other queries)

### ISSUE THREAD

**Issue by leinardi** [cyring/CoreFreq#216]
When running `corefreq-cli -c` I get some very strange DTS temperature (636) with my Ryzen 5800X:

```
CPU Freq(MHz) Ratio  Turbo  C0(%)  C1(%)  C3(%)  C6(%)  C7(%)  Min TMP:TS  Max
000  273.76 ( 2.74)   7.20   8.10  91.90   0.00   0.00   0.00  30 / 30:636/ 73
001  173.15 ( 1.73)   4.56   4.48  95.52   0.00   0.00   0.00  30 / 30:636/ 73
002  161.34 ( 1.61)   4.25   5.31  94.69   0.00   0.00   0.00  30 / 30:636/ 73
003  124.02 ( 1.24)   3.26   3.28  96.72   0.00   0.00   0.00  30 / 30:636/ 73
004   50.89 ( 0.51)   1.34   1.36  98.64   0.00   0.00   0.00  30 / 30:636/ 73
005   69.69 ( 0.70)   1.83   2.24  97.76   0.00   0.00   0.00  30 / 30:636/ 73
006   95.22 ( 0.95)   2.51   3.05  96.95   0.00   0.00   0.00  30 / 30:636/ 73
007   40.60 ( 0.41)   1.07   1.33  98.67   0.00   0.00   0.00  30 / 30:636/ 73
008   29.00 ( 0.29)   0.76   0.95  99.05   0.00   0.00   0.00  30 / 30:636/ 73
009   41.00 ( 0.41)   1.08   1.05  98.95   0.00   0.00   0.00  30 / 30:636/ 73
010  142.42 ( 1.42)   3.75   4.74  95.26   0.00   0.00   0.00  30 / 30:636/ 73
011  149.43 ( 1.49)   3.93   3.93  96.07   0.00   0.00   0.00  30 / 30:636/ 73
012  118.45 ( 1.18)   3.12   3.35  96.65   0.00   0.00   0.00  30 / 30:636/ 73
013   41.19 ( 0.41)   1.08   1.28  98.72   0.00   0.00   0.00  30 / 30:636/ 73
014   28.69 ( 0.29)   0.76   0.91  99.09   0.00   0.00   0.00  30 / 30:636/ 73
015   70.94 ( 0.71)   1.87   2.37  97.63   0.00   0.00   0.00  30 / 30:636/ 73

    Averages:        Turbo  C0(%)  C1(%)  C3(%)  C6(%)  C7(%)    TjMax:    Pkg:
                      2.65   2.98  97.02   0.00   0.00   0.00      90 C    35 C
```

```
CPU Freq(MHz) Ratio  Turbo  C0(%)  C1(%)  C3(%)  C6(%)  C7(%)  Min TMP:TS  Max
000 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
001 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
002 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
003 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
004 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
005 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
006 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
007 4555.23 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
008 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
009 4555.13 (45.55) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
010 4555.21 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
011 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
012 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
013 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
014 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78
015 4555.22 (45.56) 119.88 100.00   0.00   0.00   0.00   0.00  29 / 78:1016/ 78

    Averages:        Turbo  C0(%)  C1(%)  C3(%)  C6(%)  C7(%)    TjMax:    Pkg:
                    119.88 100.00   0.00   0.00   0.00   0.00      90 C    78 C
```

**Comment by leinardi** [comment]
Never mind, looks like it's OK like this.

**Comment by cyring** [comment]
> Never mind, looks like it's OK like this.

* Indeed it is _explained_ by this formula:
https://github.com/cyring/CoreFreq/blob/5890ec7d75c6d6dd12ebc0418ad889be03a61fc4/corefreq.h#L582

  So your CPU number `000` temperature  is solved as:
```
Temp = ( (1016 * 5 / 40) - 49 ) - 0 = 78°C
```
_Let's keep this thread opened for anybody wondering about the same question._

* In addition, I would appreciate other results from your Zen3 to check my source code ?

1. The output of `Power, Current & Thermal` window to verify `TjMax TDP Min Max PPT EDC TDC`
2. The output of the power consumed with all CPUs stressed by  `Conic Compute > Hyperboloid of two sheets` from the  `Tools` menu

  _You can put both answers in a single screenshot like mine bellow_
![2021-01-16-214001_644x1012_scrot](https://user-images.githubusercontent.com/11563789/104822607-bd77ec80-583b-11eb-9718-1f744472f99d.png)

3. Do you mind also to show me the resulted CPU Topology with the `Voltage` view  

_Press shortcut keys [`V`] then [`m`] . You can move the window with [SHIFT] + [Arrows]_  
![2021-01-16-215549_644x1012_scrot](https://user-images.githubusercontent.com/11563789/104822836-6d9a2500-583d-11eb-8330-78b8aeddf32c.png)

In advance, thank you.

**Comment by leinardi** [comment]
Hey sure, no problem:

1.  ![image](https://user-images.githubusercontent.com/273338/104839129-8a773c80-58bf-11eb-8ddb-d11cbef792d0.png)
2. ![image](https://user-images.githubusercontent.com/273338/104839165-b692bd80-58bf-11eb-97ce-8d5f8709318e.png)
3. ![image](https://user-images.githubusercontent.com/273338/104839186-d3c78c00-58bf-11eb-9791-46d4d79e94d9.png)

Let me know if you need anything else.

**Comment by cyring** [comment]
Hello,

In this [thread](https://www.overclock.net/threads/corefreq-call-for-ryzen-5900-testers.1776015/post-28763410), something odd encountered with a Vermeer Ryzen 5 5600X.
Total CPU count is one !

Whatever the SMT state is, don't you have such bug with the 5800X, do you ?

**Comment by cyring** [comment]
Hi @leinardi 
Original `DTS` question seems covered. I believe we can close the issue.
Without a Vermeer processor, I can't tell if other _CoreFreq_ features are unavailable.
My assumption is that Vermeer may be the same registers as Matisse.
