### ISSUE TITLE
archlinux installation instructions are out of date

### ISSUE THREAD

**Issue by pmav99** [cyring/CoreFreq#228]
Just what the title says. The old package has been removed and now there are 3 different packages on AUR now. Instructions should probably be updated or removed.

**Comment by inglor** [comment]
Hi @pmav99 I'm the maintainer of the AUR packages. The split was done to follow the guidelines of the Archlinux regarding AUR packages.

Currently the [corefreq] pkgbase is not compatible with `5.12` kernel so you can use [corefreq-git] which tracks `develop` branch (currently compatible with `5.12`

[corefreq]: https://aur.archlinux.org/pkgbase/corefreq/ 
[corefreq-git]: https://aur.archlinux.org/pkgbase/corefreq-git/
