### ISSUE TITLE
Update AUR links in readme

### ISSUE THREAD

**Issue by RealStickman** [cyring/CoreFreq#244]
The packages `corefreq` and `corefreq-git` don't exist any more in the AUR.  
Instead, they have been split into `corefreq-client`, `corefreq-server` and `corefreq-dkms` with git-versions available as well.  
`corefreq-client` provides the full program as it pulls the other two as dependencies and is probably what most people want.

**Comment by cyring** [comment]
Indeed CoreFreq has a new AUR package maintainer.
Thanks to @inglor who I believe may help with this issue.

**Comment by inglor** [comment]
@RealStickman What's the issue though? Readme already refers to them and has links. The split package is only one PKGBUILD and the link points to the `pkgbase`.

**Comment by RealStickman** [comment]
I was confused because the link in the readme points to a package base instead of an actual package.  
The AUR helpers I tried can't install the package with the name `corefreq`.  
The proper, `makepkg` way works though, so feel free to close this issue.
