### ISSUE TITLE
Pentium J3710 on ASRock J3710-ITX

### ISSUE THREAD

**Issue by ich777** [cyring/CoreFreq#259]
![1](https://user-images.githubusercontent.com/28066518/122686527-c5382480-d211-11eb-881b-df8fe1e99b69.PNG)
![2](https://user-images.githubusercontent.com/28066518/122686528-c5d0bb00-d211-11eb-800c-1f4d0ff6d316.PNG)
![3](https://user-images.githubusercontent.com/28066518/122686529-c5d0bb00-d211-11eb-8339-051de43a3447.PNG)
![4](https://user-images.githubusercontent.com/28066518/122686530-c6695180-d211-11eb-8a77-a0cadbb4a836.PNG)
![5](https://user-images.githubusercontent.com/28066518/122686531-c6695180-d211-11eb-9a38-f826d5f8b371.PNG)
![6](https://user-images.githubusercontent.com/28066518/122686532-c6695180-d211-11eb-91dc-4b466a0a36da.PNG)

[lscpu.txt](https://github.com/cyring/CoreFreq/files/6682990/lscpu.txt)
[lspci.txt](https://github.com/cyring/CoreFreq/files/6682991/lspci.txt)
[motherboard.txt](https://github.com/cyring/CoreFreq/files/6682992/motherboard.txt)

`dmidecode -t memory`:

```# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x000B, DMI type 16, 23 bytes
Physical Memory Array
        Location: System Board Or Motherboard
        Use: System Memory
        Error Correction Type: None
        Maximum Capacity: 8 GB
        Error Information Handle: Not Provided
        Number Of Devices: 2

Handle 0x000D, DMI type 17, 40 bytes
Memory Device
        Array Handle: 0x000B
        Error Information Handle: Not Provided
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 8 GB
        Form Factor: DIMM
        Set: None
        Locator: A1_DIMM0
        Bank Locator: A1_BANK0
        Type: DDR3
        Type Detail: Unknown
        Speed: 1600 MT/s
        Manufacturer: Kingston        
        Serial Number: 13062223  
        Asset Tag: A1_AssetTagNum0
        Part Number: 99U5428-018.A00LF 
        Rank: 2
        Configured Memory Speed: 1600 MT/s
        Minimum Voltage: 1.35 V
        Maximum Voltage: 1.5 V
        Configured Voltage: 1.35 V

Handle 0x000F, DMI type 17, 40 bytes
Memory Device
        Array Handle: 0x000B
        Error Information Handle: Not Provided
        Total Width: Unknown
        Data Width: 64 bits
        Size: No Module Installed
        Form Factor: DIMM
        Set: None
        Locator: A1_DIMM1
        Bank Locator: A1_BANK1
        Type: Unknown
        Type Detail: Unknown
        Speed: Unknown
        Manufacturer: A1_Manufacturer1
        Serial Number: A1_SerNum1
        Asset Tag: A1_AssetTagNum1
        Part Number: Array1_PartNumber1
        Rank: Unknown
        Configured Memory Speed: Unknown
        Minimum Voltage: Unknown
        Maximum Voltage: Unknown
        Configured Voltage: Unknown```

**Comment by cyring** [comment]
Thank you.

CoreFreq enhancements here are:
* IMC decoder
* Uncore counter
* Turbo boost not capable [ark](https://ark.intel.com/content/www/us/en/ark/products/91532/intel-pentium-processor-j3710-2m-cache-up-to-2-64-ghz.html)

**Comment by cyring** [comment]
# Vcore
* Stressing a single or all Core(s), voltage should fall within this range:
![2021-06-22-112922_530x96_scrot](https://user-images.githubusercontent.com/11563789/122901113-87401b00-d34d-11eb-8295-d248276f4d1c.png)
![2021-06-22-113101_533x286_scrot](https://user-images.githubusercontent.com/11563789/122901130-8ad3a200-d34d-11eb-92dd-53757e5a3e42.png)
* CoreFreq integrated stress tool can help to verify if its formula is well calibrated ?
  If not, please let me know about your lowest and highest values.
# Power and TjMax
* TDP is expected to be at most `6W` and Thermal junction at `90°C`
![2021-06-22-113959_553x79_scrot](https://user-images.githubusercontent.com/11563789/122902258-a25f5a80-d34e-11eb-847a-03f319236637.png)
* Values should match in the window "Power, Current & Thermal" ( or press shortcut [`w`] )

**Comment by cyring** [comment]
Changes have been brought regarding https://github.com/cyring/CoreFreq/issues/259#issuecomment-864608848
Feel free to come back when you have a chance to try the latest development version.
