### ISSUE TITLE
AMD PRO A6-8570 R5, 8 COMPUTE CORES 2C+6G

### ISSUE THREAD

**Issue by cyring** [cyring/CoreFreq#265]
@svmlegacy
Very instructive, especially the enumeration of P-states.
**Thank you**. 

I can add temperature and other remaining features. Are you ok for testings ?

CyrIng

**Comment by svmlegacy** [comment]
@cyring This machine is currently on my test bed, so I can test any changes immediately.

**Comment by svmlegacy** [comment]
[AMD PRO A6-8570 lspci -nn](https://gist.github.com/svmlegacy/b1fbd46164393ffb69ac6a4e668ae5d8)

**Comment by cyring** [comment]
Hi,

Can you pull and try latest `develop` branch which contains this commit aee2a52be60f15a427b36c96709f5bb12258f739 for temperature sensor.

Please don't let any other SMU drivers run in parallel. Unload `k10temp`

CyrIng

**Comment by svmlegacy** [comment]
[Looks like we have a temp sensor!](https://gist.github.com/svmlegacy/26c0b9a3e1fe3739c082412c50cc8815)

This is Tctl, correct? Not actual package temp? (Though 19 would be pretty close.)

**Comment by cyring** [comment]
> [Looks like we have a temp sensor!](https://gist.github.com/svmlegacy/26c0b9a3e1fe3739c082412c50cc8815)
> 
> This is Tctl, correct? Not actual package temp? (Though 19 would be pretty close.)

Great!

Can't really tell from here, but stressing Core(s) may give us a hint about the max temp is about  what ? die or package ?

Value is coming from SMU and I don't see how to specify a query per CPU. I'm relying on your observations to define what kind of sensor it is.

By the end if we just have one sensor then the temperature default scope will be set to "Package" in source code.

**Comment by svmlegacy** [comment]
> > [Looks like we have a temp sensor!](https://gist.github.com/svmlegacy/26c0b9a3e1fe3739c082412c50cc8815)
> > This is Tctl, correct? Not actual package temp? (Though 19 would be pretty close.)
> 
> Great!
> 
> Can't really tell from here, but stressing Core(s) may give us a hint about the max temp is about what ? die or package ?
> 
> Value is coming from SMU and I don't see how to specify a query per CPU. I'm relying on your observations to define what kind of sensor it is.
> 
> By the end if we just have one sensor then the temperature default scope will be set to "Package" in source code.

AMD's Family 15h has a rather strange temperature sensor in my experience. The sensor here actually is one of the most sensible values I've seen from it. This is a pretty low power chip, but I'm seeing roughly ambient temperature at idle, and ~ 40 C max temp under Prime95 loading. Locking up the fan, I'm seeing throttle at 94 C, again a very sensible value.

I don't believe Family 15h has a sensor for each individual core at any rate. I've never seen a tool report that.

**Comment by cyring** [comment]
So I will show as a Package scope in next UI commit.

**Comment by cyring** [comment]
I had programmed the `C1E` state query and the ability to alter it but, because based on K8 register, I left it as Experimental:

https://github.com/cyring/CoreFreq/blob/dbc6ebcfad9cfad11047da17e775806c70a41470/corefreqk.c#L9623

From the UI could you enable the `Settings > Experimental` mode (or using the driver start-up option of same name)

Next toggle ON and OFF the C1E from the `Performance Monitoring` window.

Thank you.

**Comment by svmlegacy** [comment]
![image](https://user-images.githubusercontent.com/59940364/123553572-f2bd2a80-d749-11eb-98eb-1c9b9db7a336.png)
C1E does not seem to be able to toggle "ON" for this system. This is the latest develop build.

**Comment by cyring** [comment]
> ![image](https://user-images.githubusercontent.com/59940364/123553572-f2bd2a80-d749-11eb-98eb-1c9b9db7a336.png)
> C1E does not seem to be able to toggle "ON" for this system. This is the latest develop build.

Thanks for trying.

**Comment by cyring** [comment]
Hello,

Latest commits in `develop` bring the following features for all AMD families:
1. the Watchdog state which can be toggle ON/OFF (in `Technologies` window)
2. the I/O C-State Base Address (in `Performance Monitoring` window)
  when you register _CoreFreq_ as the kernel idle handler to do I/O WAIT

The default temperature scope is now `Package`

**Comment by cyring** [comment]
Released.
