### ISSUE TITLE
trap divide error ?

### ISSUE THREAD

**Issue by jowa2021** [cyring/CoreFreq#287]
Hello,

I was wondering if you had any advice on the following snip from dmesg when loading this phenomenal tool?
![image](https://user-images.githubusercontent.com/80190819/138649942-403b1133-9230-46e5-8cad-5d91669ac2a0.png)

Also,  if you would happen to know why my pci dev's are listed as skylake ??

![image](https://user-images.githubusercontent.com/80190819/138650210-99effc0f-c4f0-45ab-9967-c8c3676e8f53.png)

Thank you for your time

**Comment by cyring** [comment]
New version is awaiting for your answer. Do you still have the issue ?

**Comment by cyring** [comment]
Do you still have your issue ?

**Comment by cyring** [comment]
Closing the issue b/c no answer.

Will try to find a way to reach such Xeon family ...
