### ISSUE TITLE
System freezes when trying to insert the module

### ISSUE THREAD

**Issue by RomuloPBenedetti** [cyring/CoreFreq#30]
kernel : 4.13.0-0.rc1.git0.1.fc27.x86_64

**Comment by cyring** [comment]
Does it also with the previous 4.11 kernel ?
If yes, what is you processor brand & model ?

**Comment by RomuloPBenedetti** [comment]
Yes, same in 4.11.10-300.fc26.x86_64, it is an Intel i7 6700 non k, just to add, I'm in process of recalling it, some problems with SVID, as I don't know if it can affect CoreFreq.

**Comment by cyring** [comment]
I'm not sure I can help with faulty processors.

**Comment by cyring** [comment]
Hello,
The closed issue #30 already solved SkyLake.
