### ISSUE TITLE
[SOLVED][AMD/EPYC/Rome] Wrong Registers reading on second socket

### ISSUE THREAD

**Issue by cyring** [cyring/CoreFreq#302]
* Temperature
![CaptureScreen (6)](https://user-images.githubusercontent.com/11563789/144758616-1ce96481-95fe-48f1-a15a-6678cc9a76ad.jpeg)
![CaptureScreen (7)](https://user-images.githubusercontent.com/11563789/144758619-2515e004-7149-412a-b087-89576ee65729.jpeg)

**Comment by cyring** [comment]
https://github.com/cyring/CoreFreq/blob/478eee81930e1c339f13787a17d7d0ffe2231e2d/corefreqk.c#L11223
* Need to verify the CCD topology.

**Comment by cyring** [comment]
* The CPU topology issue

![CaptureScreen1](https://user-images.githubusercontent.com/11563789/145672492-b100ff16-0a9a-4612-960e-515f6562a0a2.jpeg)
![CaptureScreen2](https://user-images.githubusercontent.com/11563789/145672522-5dfddc25-8401-4b7f-8dce-8f681af728d3.jpeg)
![CaptureScreen3](https://user-images.githubusercontent.com/11563789/145672545-ce137ad4-5850-450c-8acd-77de6c6728e6.jpeg)
![CaptureScreen4](https://user-images.githubusercontent.com/11563789/145672566-d1a5d1cd-beb3-4bac-89fd-fd58dd87f356.jpeg)

**Comment by cyring** [comment]
Still part of the `develop` branch, the fix is showing off in this [gist](https://gist.github.com/cyring/31090bde7ff0c276db08f4b4dd8d0915)

**Comment by jowa2021** [comment]
Hello sir, this is recent from AMD system, suspect that my kernel having keys disabled or somthing is causing the issue....
after this point, kernel panic and reboot.

![image](https://user-images.githubusercontent.com/80190819/146310585-b0680d50-a57b-472e-a310-b76e43a659d2.png)

**Comment by cyring** [comment]
> Hello sir, this is recent from AMD system, suspect that my kernel having keys disabled or somthing is causing the issue.... after this point, kernel panic and reboot.
> 
> ![image](https://user-images.githubusercontent.com/80190819/146310585-b0680d50-a57b-472e-a310-b76e43a659d2.png)

I don't see in your issue something about _CoreFreq_ !
But if signed kernel drivers is the purpose, you'll find various readings in kernel documentation.
My `Makefile` does not sign, you have to do it by your own.
The easier and most common way to get ride of a secured boot is to set some BIOS features:
* Disable safe boot
* Enable CSM (with UEFI support)

**Comment by jowa2021** [comment]
![image](https://user-images.githubusercontent.com/80190819/147356031-9f188d71-d916-4c7e-8218-ea48fefbdf29.png)
hello, can you help to figure out what RDL column is please ?

**Comment by cyring** [comment]
> hello, can you help to figure out what RDL column is please ?

[overclock.net](https://www.overclock.net/threads/tphyrdl-changed.1794471/post-28878129)

![2021-12-25-004103_802x42_scrot](https://user-images.githubusercontent.com/11563789/147374332-aae311a8-beaa-46b6-8d73-a1f258585e93.png)
![2021-12-25-004207_759x90_scrot](https://user-images.githubusercontent.com/11563789/147374344-b6821896-f95d-4f9d-a12b-bc949c0ff1a6.png)

**Comment by cyring** [comment]
* Updates from the EPYC/Rome since reverting commit  f1e9a8aad7c48fb5faacde08e1fe691a55fab349
* Topology fix
![CaptureScreen (1)](https://user-images.githubusercontent.com/11563789/147664322-7b51494a-bc53-436e-b97b-89581c85c0a6.jpeg)
* Sensors
![CaptureScreen (5)](https://user-images.githubusercontent.com/11563789/147664669-f02fe16b-375a-4cd8-abc8-f5ecfb83e59c.jpeg)
![CaptureScreen (4)](https://user-images.githubusercontent.com/11563789/147664670-27b74708-7e5e-43b4-bf8d-4fe9d50c19dc.jpeg)
* Temperature per CCD
![CaptureScreen (12)](https://user-images.githubusercontent.com/11563789/147665695-4bdea1aa-987a-43f6-b026-0a9ea020751b.jpeg)
* Memory Controller
  DIMM size remain an issue; other timings are OK
![CaptureScreen (6)](https://user-images.githubusercontent.com/11563789/147664804-427ae2ac-a6a4-4b8b-bfa1-b1305fd40ef7.jpeg)
* Performance Monitoring
![CaptureScreen (7)](https://user-images.githubusercontent.com/11563789/147664899-d6e42a43-9361-46a4-9b3a-0bccbef8991f.jpeg)
* Power, Current & Thermal
  PPT, others need a review against specs
![CaptureScreen (8)](https://user-images.githubusercontent.com/11563789/147665073-94c5595c-86fe-4456-b9ee-1c471a2dce8f.jpeg)
* Like all Ryzen, MWAIT a bit toasty, I/O is preferred (See Vcore & Temp in bottom, right)
![CaptureScreen (9)](https://user-images.githubusercontent.com/11563789/147665199-90cf9624-11d9-476d-bff5-4c376c1008cb.jpeg)
![CaptureScreen (11)](https://user-images.githubusercontent.com/11563789/147665397-6831a5d8-bc5c-48a4-a584-285b359474f4.jpeg)
* Switching OFF/ON cache prefetchers
![CaptureScreen (13)](https://user-images.githubusercontent.com/11563789/147665975-129fc9a6-7c8a-4fd0-89b2-3ebb62987123.jpeg)
![CaptureScreen (14)](https://user-images.githubusercontent.com/11563789/147665980-a8bb7480-e122-46eb-a7e6-32fc85a8aa72.jpeg)
