### ISSUE TITLE
[SOLVED] Project-C patch makes corefreq fail compilation in 5.16.x

### ISSUE THREAD

**Issue by inglor** [cyring/CoreFreq#322]
Although officially the projectc [1] hasn't officially published any new patchset for `5.16` users ported this into the latest 5.16 branch [2] [3] [4] [5]. 
Also zen-kernel ported this as well here: https://github.com/zen-kernel/zen-kernel/blob/5.16/prjc/include/linux/sched.h

With changes happening from 5.16 the `task_struct` remove the `cpu` field [6] which results in a compilation error.

[1]: https://gitlab.com/alfredchen/projectc
[2]: https://gitlab.com/alfredchen/linux-prjc/-/issues/47
[3]: https://github.com/sirlucjan/kernel-patches/tree/master/5.16/prjc-patches
[4]: https://github.com/sirlucjan/kernel-patches/tree/master/5.16/prjc-patches-v2
[5]: https://github.com/sirlucjan/kernel-patches/tree/master/5.16/prjc-patches-v3
[6]: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.16.y&id=bcf9033e5449bdcaa9bed46467a7141a8049dadb

**Comment by cyring** [comment]
> 

The _CoreFreq_ driver part is making use of `cpu` on these lines:
https://github.com/cyring/CoreFreq/blob/b9fa2c12f8b8c51a3399a7b5db1d01317f7fca61/corefreqk.c#L10187
````c
#if defined(CONFIG_SCHED_BMQ) \
 || defined(CONFIG_SCHED_PDS)
		SysGate->taskList[cnt].wake_cpu = (short int) thread->cpu;
#else
		SysGate->taskList[cnt].wake_cpu = (short int) thread->wake_cpu;
#endif /* CONFIG_SCHED_BMQ	*/
````
Not sure about the impacts from the Project-C patchset but if changes can be solved with `wake_cpu` then it is just a matter of adding a Project-C build definition to the condition `#if defined(CONFIG_SCHED_BMQ) || defined(CONFIG_SCHED_PDS)`
According to the zen-kernel, `CONFIG_SCHED_ALT` should be the one.
I don't have a Project-C environment, can you try with `CONFIG_SCHED_ALT` ?

**Comment by inglor** [comment]
Project-C is the "new" name of the BMQ scheduler which by itself derived from PDS (and PDS-mq): https://cchalpha.blogspot.com/2020/06/project-c-repositories.html

**Comment by cyring** [comment]
> Project-C is the "new" name of the BMQ scheduler which by itself derived from PDS (and PDS-mq): https://cchalpha.blogspot.com/2020/06/project-c-repositories.html

Without `CONFIG_SCHED_ALT` in your `.config`, `wake_cpu` appears usuable.
https://gitlab.com/alfredchen/linux-prjc/-/blob/linux-5.15.y-prjc/include/linux/sched.h#L762
Can you post what you get as build error output ?

**Comment by inglor** [comment]
Sure, this is from trying to generate the kernel module with `dkms` from 1.89.3 against the `linux-prjc` 5.16.8.
```
make: Entering directory '/usr/src/corefreq-1.89.3'
cc   corefreqd.c corefreqm.c \
  -D CORE_COUNT=256 -D TASK_ORDER=5 -D MAX_FREQ_HZ=5250000000 -D UBENCH=0 \
  -o corefreqd -lpthread -lm -lrt
cc   \
  corefreq-cli.c corefreq-ui.c corefreq-cli-rsc.c \
  corefreq-cli-json.c corefreq-cli-extra.c \
  -D CORE_COUNT=256 -D TASK_ORDER=5 -D MAX_FREQ_HZ=5250000000 -D UBENCH=0  \
  -o corefreq-cli -lm -lrt
make -j1 -C /usr/lib/modules/5.16.8-1-prjc/build M=/var/lib/dkms/corefreq/1.89.3/build modules
make[1]: Entering directory '/usr/src/corefreq-1.89.3'
make[1]: warning: -j1 forced in submake: resetting jobserver mode.
  CC [M]  /var/lib/dkms/corefreq/1.89.3/build/corefreqk.o
/var/lib/dkms/corefreq/1.89.3/build/corefreqk.c: In function ‘Sys_DumpTask’:
/var/lib/dkms/corefreq/1.89.3/build/corefreqk.c:10190:71: error: ‘struct task_struct’ has no member named ‘wake_cpu’; did you mean ‘wake_q’?
10190 |                 SysGate->taskList[cnt].wake_cpu = (short int) thread->wake_cpu;
      |                                                                       ^~~~~~~~
      |                                                                       wake_q
compilation terminated due to -Wfatal-errors.
make[2]: *** [scripts/Makefile.build:287: /var/lib/dkms/corefreq/1.89.3/build/corefreqk.o] Error 1
make[1]: *** [Makefile:1846: /var/lib/dkms/corefreq/1.89.3/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.16.8-1-prjc/build'
make: *** [Makefile:76: all] Error 2
make: Leaving directory '/usr/src/corefreq-1.89.3'
```
You can check it yourself if you install the packages from my unofficial repository:
https://wiki.archlinux.org/title/Unofficial_user_repositories#artafinde

[linux-prjc](https://pkgbuild.com/~artafinde/repo/linux-prjc-5.16.8-1-x86_64.pkg.tar.zst)
[linux-prjc-headers](https://pkgbuild.com/~artafinde/repo/linux-prjc-headers-5.16.8-1-x86_64.pkg.tar.zst)
[corefreq-client](https://pkgbuild.com/~artafinde/repo/corefreq-client-1.89.3-1-x86_64.pkg.tar.zst)
[corefreq-dkms](https://pkgbuild.com/~artafinde/repo/corefreq-dkms-1.89.3-1-x86_64.pkg.tar.zst)
[corefreq-server](https://pkgbuild.com/~artafinde/repo/corefreq-server-1.89.3-1-x86_64.pkg.tar.zst)

Pacman can support installing from urls if you don't want to install a whole repo.
```
pacman -U /url/to/package1 /url/to/package2 ...
```

**Comment by cyring** [comment]
Ok let me try to build with your package

**Comment by cyring** [comment]
```
pacman -Syu --ignore=linux --ignore=linux-docs --ignore=linux-headers --ignore=archiso
git clone https://aur.archlinux.org/linux-prjc.git
cd linux-prjc
makepkg -cCsfir
```
```
:: Retrieving packages...
 python-idna-3.3-3-any.pkg.tar.zst failed to download
error: failed retrieving file 'python-idna-3.3-3-any.pkg.tar.zst' from mir.archlinux.fr : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
```
```
==> Validating source files with b2sums...
    linux-5.16.8.tar.xz ... Passed
    linux-5.16.8.tar.sign ... Skipped
    linux-prjc-5.16.8-config ... Passed
    prjc_v5.16.patch ... Passed
    more-uarches-20211114.tar.gz ... Passed
    0001-linux-prjc-5.16.8-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ... FAILED
    0002-linux-prjc-5.16.8-Bluetooth-btintel-Fix-bdaddress-comparison-with-garb.patch ... FAILED
    0003-linux-prjc-5.16.8-Bluetooth-Read-codec-capabilities-only-if-supported.patch ... FAILED
    0003-linux-prjc-5.16.8-Bluetooth-fix-deadlock-for-RFCOMM-sk-state-change.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
```
---
```
pacman -S python-idna
makepkg_subarch=12  -cCsfir --skipchecksums
```
6 minutes of build and install later ... Now booting `linux-prjc`

**Comment by cyring** [comment]
* Raw results with the following change:
```
#if defined(CONFIG_SCHED_ALT)
		SysGate->taskList[cnt].wake_cpu = (short int) thread->on_cpu;
#elif defined(CONFIG_SCHED_BMQ) || defined(CONFIG_SCHED_PDS)
		SysGate->taskList[cnt].wake_cpu = (short int) thread->cpu;
#else
		SysGate->taskList[cnt].wake_cpu = (short int) thread->wake_cpu;
#endif /* CONFIG_SCHED_BMQ	*/
```
---
* last CPU stressed
```
taskset -c 31 7z b
```
![2022-02-10-234140_644x550_scrot](https://user-images.githubusercontent.com/11563789/153508985-b5e578c9-1218-4870-92a0-f9f423430da1.png)
* idle case

![2022-02-10-234424_644x550_scrot](https://user-images.githubusercontent.com/11563789/153509283-3bc2da8b-246c-4600-afd1-f4e6b753f915.png)
---
Ugh, `thread->on_cpu` is definitively not the good candidat for tasks monitoring

**Comment by cyring** [comment]
Now you test from the branch `develop`

**Comment by inglor** [comment]
Yeah I can confirm the `develop` branch works fine

**Comment by cyring** [comment]
Built `5.16.9-1-prjc`: no regression observed with `develop` branch

![2022-02-17-000256_1284x550_scrot](https://user-images.githubusercontent.com/11563789/154372367-96c8ba95-d4b5-4dd3-95c7-de3182f2cc85.png)

Btw, I have to add `--skipchecksums` option to `makepkg`

**Comment by inglor** [comment]
@cyring It seems 1.89.4 doesn't have the patch for this issue. I was expecting it to be there since the tag was made after your commit. Is that intentional?

**Comment by cyring** [comment]
> @cyring It seems 1.89.4 doesn't have the patch for this issue. I was expecting it to be there since the tag was made after your commit. Is that intentional?

Still part of the [`develop`](https://github.com/cyring/CoreFreq/commit/2bf03e69c8b679eec90826012da4a63afb193872) branch. I wasn't aware you need it immediately. 
If you are blocked then I have to release `1.90` ASAP. Do you want me to ?

**Comment by inglor** [comment]
Nope, it's fine keep working on the new intel chps on `develop` and I can just backport that commit. Thanks for the reply ;)

**Comment by cyring** [comment]
I think we can close this one.
