### ISSUE TITLE
Module corefreqk.ko could not be inserted

### ISSUE THREAD

**Issue by Ricky-Tigg** [cyring/CoreFreq#348]
_OS:_ Fedora

Hello. Illustration of the issue:
```
$ uname -ro
5.18.6-200.fc36.x86_64 GNU/Linux
$ sudo dnf -y install @development-tools
$ ps -af | grep "[d]og"
$ git clone https://github.com/cyring/CoreFreq.git
$ cd CoreFreq && make
(...)
$ sudo insmod corefreqk.ko
insmod: ERROR: could not insert module corefreqk.ko: Key was rejected by service
```

**Comment by cyring** [comment]
> _OS:_ Fedora
> 
> Hello. Illustration of the issue:
> 
> ```
> $ uname -ro
> 5.18.6-200.fc36.x86_64 GNU/Linux
> $ sudo dnf -y install @development-tools
> $ ps -af | grep "[d]og"
> $ git clone https://github.com/cyring/CoreFreq.git
> $ cd CoreFreq && make
> (...)
> $ sudo insmod corefreqk.ko
> insmod: ERROR: could not insert module corefreqk.ko: Key was rejected by service
> ```

#350
