### ISSUE TITLE
Performance mode?

### ISSUE THREAD

**Issue by gel-crabs** [cyring/CoreFreq#349]
Is there an equivalent to CPUFreq's performance mode with CoreFreq (Essentially forcing max all-core frequency)? I have CPUFreq turned off so CoreFreq can replace it.

I am running Ryzen, Zen+ if that makes a difference. Thank you

**Comment by cyring** [comment]
> Is there an equivalent to CPUFreq's performance mode with CoreFreq (Essentially forcing max all-core frequency)? I have CPUFreq turned off so CoreFreq can replace it.
> 
> I am running Ryzen, Zen+ if that makes a difference. Thank you

#350

**Comment by gel-crabs** [comment]
If anybody is wondering, I found out how to do so.
`cpupower idle-set -D 1` to enable it, `cpupower idle-set -E` to disable it.

**Comment by cyring** [comment]
But _CoreFreq_ is providing the same.

Performance is tunable through `/sys`
Just dig to find them. 

If not enough kernel parameters provides performance hints

When registered as OS CPU-Freq (see Readme), driver maintains hardware registers coherence, wherever the change comes from `sys` ; UI


I've explain these many times in Issues and Wiki and I won't answer about cpu_tools



As usual I need your issue with CoreFreq outputs and screenshots for your use case purpose.

**Comment by cyring** [comment]
> The cpupower command disables all idle states through CPU-Idle and forces all cores to max all-core frequency. It doesn't involve CPUFreq.
> 
> My use-case is for gaming, some games (such as Garry's Mod) aren't very good at telling the OS when it needs work done. I'm using those commands through GameMode so it resets back to normal when I'm not gaming.

Are you aware about this mode:
```
insmod corefreqk.ko Register_CPU_Idle=1
```
And there are other P-states you can combine.

Every thing you tune from UI can be permanently set to driver.

* Turbo and Target P-states
```
parm:           Ratio_Boost:Turbo Boost Frequency ratios (array of int)
parm:           Ratio_PPC:Target Performance ratio (int)
```

**Comment by cyring** [comment]
See use case at https://github.com/cyring/CoreFreq/discussions/345#discussioncomment-2989565

**Comment by gel-crabs** [comment]
> > The cpupower command disables all idle states through CPU-Idle and forces all cores to max all-core frequency. It doesn't involve CPUFreq.
> > My use-case is for gaming, some games (such as Garry's Mod) aren't very good at telling the OS when it needs work done. I'm using those commands through GameMode so it resets back to normal when I'm not gaming.
> 
> Are you aware about this mode:
> 
> ```
> insmod corefreqk.ko Register_CPU_Idle=1
> ```
> 
> And there are other P-states you can combine.
> 
> Every thing you tune from UI can be permanently set to driver.
> 
> * Turbo and Target P-states
> 
> ```
> parm:           Ratio_Boost:Turbo Boost Frequency ratios (array of int)
> parm:           Ratio_PPC:Target Performance ratio (int)
> ```

I'm using Register_CPU_Idle=1, I have it governing everything

Thank you for the explanation of Ratio_PPC, are the kernel parameters on-the-fly? I'm not setting this permanently

**Comment by cyring** [comment]
> Thank you for the explanation of Ratio_PPC, are the kernel parameters on-the-fly? I'm not setting this permanently

`Ratio_PPC` like all `corefreq.ko` parameters are applied during driver startup

On-the-fly, when properly registered, you change through the `/sys/.../cpu/corefreq/.../param` (_plz find your path_)
You should find to change ratios, some are Read-Write, others R/O.

My `SysFS` implementation has the advantage to aggregate features. Changes are dynamically visible in the UI and vice versa.

**Comment by gel-crabs** [comment]
Thank you. Is there a way to change Kernel Data -> Idle Limit on the fly?

https://imgur.com/a/O0dRpuA

**Comment by gel-crabs** [comment]
Also should I close this?

**Comment by cyring** [comment]
* If I understand your need, is this a standard Linux command ? 

`echo $limit > /sys/` 

Once changed, just press the`*` shortkey in the UI to invoke a full refresh. 

* Yes issue can be closed. Things not being a source code programming issue like general usage would be better takes place in:

https://github.com/cyring/CoreFreq/discussions
