### ISSUE TITLE
dual-socket CPU power: Core power is greater than package?

### ISSUE THREAD

**Issue by Rimits** [cyring/CoreFreq#359]
Is it normal or a bug that Core Power 279W is greater than Package Power 210W ?

OS:ubuntu 20.04
CoreFreq version: 1.91.5
CPU: epyc 7542 *2
Motherboard: Gigabyte
![截屏_20220810-105720](https://user-images.githubusercontent.com/42634955/183816169-c065b6c6-94e8-4525-854a-a816cf05e228.png)

**Comment by cyring** [comment]
It is not normal and dual EPYC is barely never tested; before your screenshot.

Need to debug: send you code changes; is your dual socket platform available for experimentation ?

**Comment by cyring** [comment]
* `Cores` watt is the sum of all **physical** Core threads. Logical SMT Cores are excluded from the sum.  
* `Package` watt is source from a hardware register

Without better specs, I think `Package` refers to one socket

**Comment by Rimits** [comment]
Of course, I can do some experiments on that server.
If I was right, the 279W of cores power is accurate, but it's the sum of all the cores of the two sockets, because the BMC shows the current and voltage of VRM_CPU0 are 142A and 0.94V.
The Pacakge power, i don't know, maybe it's showing only the power of the first socket.

**Comment by cyring** [comment]
The label `Package0` is a good suggestion.

You can also target the second socket for a `Package` watt reading.
You'll have to bind the CoreFreq Service Processor to a CPU which belongs to second socket.
1. Refer to the `Topology` to find a CPU of second socket. Let's say `64`
2. Reload the driver this way:
```sh
insmod corefreqk.ko ServiceProcessor=64

## Or adapt your modprobe
```
3. Please provides a screenshot of the `Power` view

Remarks:
* I presumed Package0 and Package1 should slightly differ ?
* When not specified, Service Processor is selected according to kernel scheduling
* Service Processor can be assigned to any socket
* If CPU is disabled, Service Processor is auto migrated by driver
* UI is always highlighting the CPU number of the Service Processor and its SMT, (and the Hybrid with Intel 12th gen.)

**Comment by cyring** [comment]
> Of course, I can do some experiments on that server. The 279W of cores power could be accurate, because the BMC shows the current and voltage of VRM_CPU0 are 142A and 0.94V. Package watt seems accurate too since the cpu is limited to 225W. Maybe appending a "0" to the `Package` label will fix the misleading situation.

`0.94V` in your readings is during idle case

Computing from my Matisse voltage of `1.48 V` (instant load voltage) and your Rome current of `142A`, I'm getting a consumed power `P = V x I` of `~ 210W`

**Comment by Rimits** [comment]
Topology:
```
 ---------------------------------- Topology ----------------------------------      
 CPU Pkg  Apic  Core/Thread  Caches      (w)rite-Back (i)nclusive              
  #   ID   ID CCD CCX ID/ID L1-Inst Way  L1-Data Way      L2  Way      L3  Way 
 000:BSP    0   0  0   0  0      32  8        32  8       512  8 i  131072 16w  
 001:  0    2   0  0   1  0      32  8        32  8       512  8 i  131072 16w 
 ...
 031:  0   62   6  7  31  0      32  8        32  8       512  8 i  131072 16w  
 ...                                          
 ------------------------------------------------------------------------------
```
Reload: `insmod corefreqk.ko ServiceProcessor=32`

Result:
![截屏_20220810-151335](https://user-images.githubusercontent.com/42634955/183839859-251c13e1-fc52-4af3-bc6f-515cef23003e.png)


When Service Processor is 19:
They are slightly different, since CPU2 is cooler and the frequency of it is higher.
![截屏_20220810-151559](https://user-images.githubusercontent.com/42634955/183839898-906b821e-6fcd-4029-9023-7a2fedac1b6f.png)

**Comment by cyring** [comment]
For your information, below specs of the two `Power` registers:  
![2022-08-10-093717_801x235_scrot](https://user-images.githubusercontent.com/11563789/183842851-3f37c952-b7b3-4fff-8b58-8e21fb6fb05a.png)
![2022-08-10-093803_802x290_scrot](https://user-images.githubusercontent.com/11563789/183843006-dddf1064-c7f5-4dfa-a2e2-56acc3d66b3d.png)

**Comment by cyring** [comment]
Hello,

Can you try this attached version where the Package ID is appended to label.
Should print `0` or `1` depending of your selected Service Processor.

[CoreFreq_develop.tar.gz](https://github.com/cyring/CoreFreq/files/9298270/CoreFreq_develop.tar.gz)

Two UI views are impacted:
* Sensors
* Power

And two CLI outputs are impacted:
* `corefreq-cli -C`
* `corefreq-cli -w`

**Comment by Rimits** [comment]
Thx, it's less confusing now.
![截屏_20220810-164917](https://user-images.githubusercontent.com/42634955/183859319-27dfb98f-e28e-44dc-af50-05491a6df7b0.png)

**Comment by cyring** [comment]
Meanwhile I have enhanced the `Custom` view
[CoreFreq_develop.tar.gz](https://github.com/cyring/CoreFreq/files/9298553/CoreFreq_develop.tar.gz)

**Comment by Rimits** [comment]
well, you do have a fast hand🚴
![截屏_20220810-171014](https://user-images.githubusercontent.com/42634955/183863062-5fa89849-002e-44f0-8fc8-1f8684cf3a24.png)

**Comment by cyring** [comment]
> well, you do have a fast handbicyclist ![截屏_20220810-171014]

Thank you. 

I'll leave those changes in the `develop` branch for a short while; making sure no regression happens on other systems.
