### ISSUE TITLE
[SOLVED] [Ubuntu 16.04] fail to build kernel module

### ISSUE THREAD

**Issue by wjc404** [cyring/CoreFreq#373]
I encountered a compilation error when trying to build the kernel module with Ubuntu 16.04. However the build was successful on another computer with Ubuntu 20.04.
![image](https://user-images.githubusercontent.com/52632443/201458118-16201317-0ebc-4630-b29f-cf47c20005bc.png)
It seems that the change of acpi cppc interface should account for the difference.
![image](https://user-images.githubusercontent.com/52632443/201458294-68bd26a9-dc88-4042-baf5-b4a2973498bc.png)

**Comment by cyring** [comment]
> I encountered a compilation error when trying to build the kernel module with Ubuntu 16.04. 

Please pull and try the [hotfix_cppc_acpi](https://github.com/cyring/CoreFreq/tree/hotfix_cppc_acpi) branch

**Comment by wjc404** [comment]
Thanks:)   What about the 4th parameter "unsigned short CPB" of function CPPC_AMD_Zen_ScaleRatio, does it have a default value ?

**Comment by cyring** [comment]
> Thanks:) What about the 4th parameter "unsigned short CPB" of function CPPC_AMD_Zen_ScaleRatio, does it have a default value ?

Please pull the branch for this fix. Thank you.

**Comment by wjc404** [comment]
Now the compilation passes. But the terminal hangs during module insertion. The CPU architecture of my computer is skylake-X. Thank again for looking at this issue. I will roll back to older version.

**Comment by cyring** [comment]
> Now the compilation passes. But the terminal hangs during module insertion. The CPU architecture of my computer is skylake-X. Thank again for looking at this issue. I will roll back to older version.

Don't you have any kernel log to show me ?
Since which version of _CoreFreq_ your SKL/X is crashing ?

**Comment by wjc404** [comment]
Well, I found nothing related in /var/log/syslog (actually the logging is stopped until I press the restart button). 

The version v1.90 RC1(commit a154015) works fine without crash.
