### ISSUE TITLE
AMD "Phoenix" ;  "Dragon Range" ; "Raphael" ; Refresh

### ISSUE THREAD

**Issue by cyring** [cyring/CoreFreq#408]
# Need CPUID!
## Phoenix `[PHX]`
* Laptop RDNA3 FP7/FP7r2/FP8 Zen4

Brand           | CPUID | UMC
----------------|-------|----
[`AMD Ryzen 9 7940HS`](https://www.amd.com/en/product/13036)| AF_74 | [LP]DDR5
[`AMD Ryzen 7 7840HS`](https://www.amd.com/en/product/13041)| AF_74 | [LP]DDR5
[`AMD Ryzen 5 7640HS`](https://www.amd.com/en/product/13046)| AF_74 | [LP]DDR5

## Phoenix `[PHX2]`
* Mobile RDNA3 Zen4

Brand           | CPUID
----------------|------
[`?`](https://www.coelacanth-dream.com/posts/2023/02/07/amd-phx-phx2-gfx1103_r1_r2/)| AF_78

## Dragon Range
* Laptop RDNA2 FL1 Zen4

Brand           | CPUID | UMC
----------------|-------|----
[`AMD Ryzen 9 7945HX`](https://www.amd.com/en/product/13016)|AF_61| DDR5
[`AMD Ryzen 9 7845HX`](https://www.amd.com/en/product/13021)|[AF_61](https://browser.geekbench.com/v6/cpu/467541)| DDR5
[`AMD Ryzen 7 7745HX`](https://www.amd.com/en/product/13026)| - | DDR5
[`AMD Ryzen 5 7645HX`](https://www.amd.com/en/product/13031)| - | DDR5

## Granite Ridge
* Zen5

**Comment by irusanov** [comment]
From coreboot: https://github.com/coreboot/coreboot/blob/8afb45e0a67581b5f8cd6a828bbd1daf54825a36/src/soc/amd/phoenix/include/soc/cpu.h
```
#define PHOENIX_A0_CPUID 0x00a70f40
#define PHOENIX2_A0_CPUID 0x00a70f80
```

**Comment by Umio-Yasuno** [comment]
> AF_78 would be GFX1103_R2
> whereas [AF_74](https://github.com/cyring/CoreFreq/blob/0f70cde61624aa0c8f161eae564009747eb795a5/corefreqk.h#L1977) is GFX1103_R1 where formulas would be the same as Rembrandt APU according to [Coelacanth's Dream](https://www.coelacanth-dream.com/posts/2023/02/07/amd-phx-phx2-gfx1103_r1_r2/)

No. CPUID Family/Model/Stepping is not linked to GFXID.  
Different SoCs may share the same GFXID, such as the Renoir/Lucienne/Cezanne_Barcelo APU. (GPU DeviceID is different)

**Comment by irusanov** [comment]
Phoenix2 seems to be the big.LITTLE project from AMD with 2 Zen4 cores and 4 Zen4C cores.
https://mobile.twitter.com/3DCenter_org/status/1622785618454675456
