### ISSUE TITLE
[Chimera] Musl libc and Clang compiler support

### ISSUE THREAD

**Issue by KyunLFA** [cyring/CoreFreq#460]
As of now attempting to compile on Musl+Clang produces the following errors and warnings (devel branch):

```
x86_64/corefreq.h:305:27: error: field has incomplete type 'struct random_data'
                     struct random_data data;
                                        ^
x86_64/corefreq.h:305:15: note: forward declaration of 'struct random_data'
                     struct random_data data;
                            ^
x86_64/corefreqd.c:1090:48: warning: format specifies type 'unsigned long' but the argument has type 'pthread_t' (aka 'struct __pthread *') [-Wformat]
                printf("    Thread [%lx] Init CYCLE %03u\n", tid, cpu);
                                    ~~~                      ^~~
x86_64/corefreqd.c:1244:46: warning: format specifies type 'unsigned long' but the argument has type 'pthread_t' (aka 'struct __pthread *') [-Wformat]
                printf("    Thread [%lx] %s CYCLE %03u\n", tid,
                                    ~~~                    ^~~
x86_64/corefreqd.c:1273:11: error: call to undeclared function 'random_r'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                    if (random_r(&RO(Shm)->Cpu[cpu].Slice.Random.data,
                        ^
x86_64/corefreqd.c:1335:48: warning: format specifies type 'unsigned long' but the argument has type 'pthread_t' (aka 'struct __pthread *') [-Wformat]
                printf("    Thread [%lx] Init CHILD %03u\n", tid, cpu);
                                    ~~~                      ^~~
x86_64/corefreqd.c:1384:46: warning: format specifies type 'unsigned long' but the argument has type 'pthread_t' (aka 'struct __pthread *') [-Wformat]
                printf("    Thread [%lx] %s CHILD %03u\n", tid,
                                    ~~~                    ^~~
x86_64/corefreqd.c:8251:19: error: incompatible pointer to integer conversion assigning to 'pid_t' (aka 'int') from 'pthread_t' (aka 'struct __pthread *') [-Wint-conversion]
        RO(Shm)->App.Svr = tid;
                         ^ ~~~
x86_64/corefreqd.c:8736:3: error: call to undeclared function 'initstate_r'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                initstate_r(    seed32,
                ^
x86_64/corefreqd.c:8736:3: note: did you mean 'initstate'?
/usr/include/stdlib.h:118:7: note: 'initstate' declared here
char *initstate (unsigned int, char *, size_t);
```

Please consider adding support for Clang and Musl libc when time and effort resources allow.

Thank you for your kind work. Cheers.

**Comment by cyring** [comment]
Hello,

FYI Clang `+` **GNU libc** are building and running fine

I will give a look to Musl. According to your compilation code, a few functions remains to wrap for compatibility mode.

**Comment by KyunLFA** [comment]
Thank you very much, I look forward to testing it!

**Comment by cyring** [comment]
> Thank you very much, I look forward to testing it!

Can you describe your environment ?
* Linux distribution
* Kernel headers package with Musl ?
* Compiler: Clang only or both Clang + GCC
* Kernel fully built with Clang ? with Musl ?

**Comment by cyring** [comment]
Some notes:
* `HAVE_RANDOM_R`
* `pacman -S musl`
* `make CC=musl-gcc clean all`

**Comment by KyunLFA** [comment]
> > Thank you very much, I look forward to testing it!
> 
> Can you describe your environment ?
> 
> * Linux distribution
> * Kernel headers package with Musl ?
> * Compiler: Clang only or both Clang + GCC
> * Kernel fully built with Clang ? with Musl ?

Sorry for the delay. 

*1 Chimera Linux
*2 Yes
*3 Clang only
*4 Yes

Chimera is a new OS I'm trying out. It's ground up LLVM+Musl.
https://chimera-linux.org/

**Comment by cyring** [comment]
The [development](https://github.com/cyring/CoreFreq/tree/develop) branch contains some code for the musl library

So far, I'm just able to build and run _CoreFreq_ for musl with ArchLinux
```sh
## as user
make CC=musl-gcc clean all
## as root
insmod CoreFreq/build/corefreqk.ko
CoreFreq/build/corefreqd -d
## as user
CoreFreq/build/corefreq-cli
```
1. There's a regression to detect the current locale with musl.
It is now forced to `"en_US.UTF-8"` (if not GLIBC) but can be changed afterward from the UI
2. Posix Thread is somehow odd within musl: misc types issue ...

The live base Chimera is downloaded and emulates with QEMU
Within the VM are installed the followed packages but `make` appears incomplete when compared to the GNU Make
```
apk add gmake bmake git clang linux-headers

git clone -b develop https://github.com/cyring/CoreFreq.git

make
```
```
make: line 35: Invalid line type
...
make: stopped
```
Can you help with those specifics of Chimera ?

**Comment by JamiKettunen** [comment]
@cyring I see you already installed `gmake` but you also need to call it as such since `bmake` is the default `make` on chimera (which only imlements the POSIX make spec afaik)

**Comment by cyring** [comment]
> @cyring I see you already installed `gmake` but you also need to call it as such since `bmake` is the default `make` on chimera (which only imlements the POSIX make spec afaik)
> 
> Btw testing on https://alpinelinux.org/ may also help as it's using musl too

I believe I have tried all binaries coming with these 2 packages but none is working as expected from a  "standard" GNU `make`
I mean any conditional instruction within my `Makefile` like `ifeq` is not recognized!

**Comment by JamiKettunen** [comment]
@cyring I just tested running `gmake` and it seems the `develop` branch Makefile uses GNU extensions for `ln` command at least (`ln -r`) which isn't implemented by either the FreeBSD coreutils (basically what Chimera uses) not `busybox` (what Alpine uses)

**Comment by cyring** [comment]
@JamiKettunen Thanks for your help.
Those GNU extensions are making the job since kernel 3.0 .
I still also have to qemu Alpine for a build test.

**Comment by cyring** [comment]
> The [development](https://github.com/cyring/CoreFreq/tree/develop) branch contains some code for the musl library
> 
> So far, I'm just able to build and run _CoreFreq_ for musl with ArchLinux
> 
> ```shell
> ## as user
> make CC=musl-gcc clean all
> ## as root
> insmod CoreFreq/build/corefreqk.ko
> CoreFreq/build/corefreqd -d
> ## as user
> CoreFreq/build/corefreq-cli
> ```
> 
> 1. There's a regression to detect the current locale with musl.
>    It is now forced to `"en_US.UTF-8"` (if not GLIBC) but can be changed afterward from the UI
> 2. Posix Thread is somehow odd within musl: misc types issue ...
> 
> The live base Chimera is downloaded and emulates with QEMU Within the VM are installed the followed packages but `make` appears incomplete when compared to the GNU Make
> 
> ```
> apk add gmake bmake git clang linux-headers
> 
> git clone -b develop https://github.com/cyring/CoreFreq.git
> 
> make
> ```
> 
> ```
> make: line 35: Invalid line type
> ...
> make: stopped
> ```
> 
> Can you help with those specifics of Chimera ?

@KyunLFA As the original author of the issue, I would to read your answer about the fix mentioned above ?

**Comment by cyring** [comment]
Chimera [ckms](https://github.com/chimera-linux/ckms) within `chimera-linux-x86_64-LIVE-20230915-gnome.iso`

```sh
doas mkdir -p /opt/src
doas chgrp anon /opt/src
doas chmod g+w /opt/src
cd /opt/src

doas apk add git nano
git clone -b develop https://github.com/cyring/CoreFreq.git
nano /opt/src/CoreFreq/ckms.ini
```
![2023-09-24-131656_644x239_scrot](https://github.com/cyring/CoreFreq/assets/11563789/3ff981fc-c47c-4027-b5f5-3aa5f86b4450)


```sh
doas apk add ckms linux-headers linux-lts-devel
doas ckms add /opt/src/CoreFreq/
```
![2023-09-24-124951_642x59_scrot](https://github.com/cyring/CoreFreq/assets/11563789/34b10837-6690-42a1-918b-2416fe215967)

```sh
doas ckms build corefreqk=1.97.0
```
![2023-09-24-131528_643x144_scrot](https://github.com/cyring/CoreFreq/assets/11563789/d33b6676-1cae-4734-80ea-f2970750c0b6)

---

@q66 May you please help with `ckms.ini` ?

**Comment by cyring** [comment]
Thread dead

**Comment by q66** [comment]
sorry, but i missed the message here - got lost among other emails 

the main issue with the ckms.ini is the module/, you have no such path in the repository so you should not be using it - just drop the -C, and the module/ prefix from the input path

the destination path should probably match the one in your dkms.conf instead of the one you used

also, initramfs should probably be set to no? does it make sense to rebuild initramfs for this module?

**Comment by cyring** [comment]
> sorry, but i missed the message here - got lost among other emails
> 
> the main issue with the ckms.ini is the module/, you have no such path in the repository so you should not be using it - just drop the -C, and the module/ prefix from the input path
> 
> the destination path should probably match the one in your dkms.conf instead of the one you used
> 
> also, initramfs should probably be set to no? does it make sense to rebuild initramfs for this module?

Thanks for your help.

I'm committing 7459602f68216cfe25ad6b406179fb8b34daef8a , the ongoing version of the `ckms.ini` which now fails at the end of the build
![2023-11-15-205143_1280x825_scrot](https://github.com/cyring/CoreFreq/assets/11563789/7811efff-1bbb-4ffb-98f8-68ab29dac0b5)

**Comment by q66** [comment]
the last section should look like this instead:

```
[module.corefreqk]
path = build
dest = kernel/drivers/misc
```

then it will build as well as install

**Comment by cyring** [comment]
> the last section should look like this instead:
> 
> ```
> [module.corefreqk]
> path = build
> dest = kernel/drivers/misc
> ```
> 
> then it will build as well as install

Thanks, it works much better:
![2023-11-16-221415_1280x825_scrot](https://github.com/cyring/CoreFreq/assets/11563789/3202c378-4ddf-4375-a1b9-acb8c4626056)

**Comment by q66** [comment]
great, i have some fixes for ckms lined up that i found while testing this, you can commit the ini file as is though

**Comment by cyring** [comment]
@KyunLFA @JamiKettunen Hello,

So far what you can do from the development branch within Chimera

```
git clone -b develop https://github.com/cyring/CoreFreq
cd CoreFreq
gmake CC=clang
```

```
doas insmod build/corefreqk.ko
doas build/corefreqd -q &
./build/corefreq-cli
```
![2023-11-16-223436_1280x825_scrot](https://github.com/cyring/CoreFreq/assets/11563789/14d4d6fa-70e3-41ab-be20-570e08986093)

**Comment by cyring** [comment]
@JamiKettunen Hello,

Does _CoreFreq_ development branch now build and run with Alpine ?

**Comment by cyring** [comment]
@JamiKettunen Feel free to come back at any time
