### ISSUE TITLE
Alpine Linux

### ISSUE THREAD

**Issue by cyring** [cyring/CoreFreq#461]
> @cyring I see you already installed `gmake` but you also need to call it as such since `bmake` is the default `make` on chimera (which only imlements the POSIX make spec afaik)
> 
> Btw testing on https://alpinelinux.org/ may also help as it's using musl too

I believe I have tried all binaries coming with these 2 packages but none is working as expected from a  "standard" GNU `make`
I mean any conditional instruction within my `Makefile` like `ifeq` is not recognized!

_Originally posted by @cyring in https://github.com/cyring/CoreFreq/issues/460#issuecomment-1728166067_

**Comment by cyring** [comment]
@JamiKettunen

Based on Virtual x86_64 [alpine-virt-3.18.3-x86_64.iso](https://alpinelinux.org/downloads/)

Host [Arch Linux `6.5.4`]
```
qemu-system-x86_64 -enable-kvm -cpu max,hv-runtime -m 2G -smp 4 -cdrom alpine-virt-3.18.3-x86_64.iso
```

Once VM booted, the following packages have been installed
```
apk add nano git make gcc musl-dev linux-headers
```

CoreFreq `Makefile` is also fixed for symbolic links
```
git clone -b develop https:\\github.com\cyring\CoreFreq.git
cd CoreFreq
nano Makefile
```
```
SYMLINK ?= ln -s
```

Now try to build.
You may have to force clean
```
rm -fr build
make
```
![2023-09-23-124340_739x495_scrot](https://github.com/cyring/CoreFreq/assets/11563789/67862ca2-2b05-4e44-a903-425eac7bf0bb)

Missing kernel module: to be continued

**Comment by JamiKettunen** [comment]
On top of using `ln -s` instead of making relative symlinks won't you have to fix the instances where `$(SYMLINK)` was used like from:
```
$(SYMLINK) Makefile $(BUILD)/Makefile
```
to:
```
$(SYMLINK) $(PWD)/Makefile $(BUILD)/Makefile
```
in https://github.com/cyring/CoreFreq/blob/develop/Makefile#L109, so that `$(BUILD)/Makefile` won't be a broken symlink?

**Comment by cyring** [comment]
* Alpine is now installed to disk to ease Linux Kernel Headers
```sh
apk update
apk upgrade
apk add linux-virt-dev
reboot
```
* CoreFreq is now build and run from a standard user
```sh
cd ~/src/CoreFreq
nano Makefile
```
```
SYMLINK ?= ln -s

prepare:
        @if [ ! -e $(BUILD)/Makefile ]; then \
                $(SYMLINK) $(PWD)/Makefile $(BUILD)/Makefile; \
        fi
```
```
rm -fr build
make
```
![2023-09-23-192951_706x115_scrot](https://github.com/cyring/CoreFreq/assets/11563789/c80aba51-521c-403a-9257-b8ef7c471dac)

**Comment by cyring** [comment]
# [Custom Kernel](https://wiki.alpinelinux.org/wiki/Custom_Kernel#Installing)
```
apk add alpine-sdk
```
* Clone the [aports tree](https://wiki.alpinelinux.org/wiki/Aports_tree)
* Fix write mode of `/var/cache/distfiles/`
* Create User keygen
* Add User to group `abuild`
* Create a branch for custom kernel
```
abuild-keygen -a -i
cd aports
git checkout -b corefreq-kernel
cd main/linux-lts
cp -vi virt.x86_64.config .config
abuild -rk
```

**Comment by cyring** [comment]
@JamiKettunen 
With your `Makefile` changes, can you now build and run _CoreFreq_ ?
Can you show the UI with its kernel window and the view in Tasks mode ?

**Comment by cyring** [comment]
No more work

**Comment by cyring** [comment]
* New parallel build

![2023-12-17-190428_1280x825_scrot](https://github.com/cyring/CoreFreq/assets/11563789/b67789d4-4f2c-4735-b50d-78bf6183a408)
