### ISSUE TITLE
Changing Idle Limit

### ISSUE THREAD

**Issue by Haregata** [cyring/CoreFreq#489]
You can change the Idle Limit in the CLI(to C6 for example), but I couldn't make it persist. Couldn't find anything in modinfo either. Perhaps there is a way to make CLI changes permanent that I am not aware of?

**Comment by cyring** [comment]
> You can change the Idle Limit in the CLI(to C6 for example), but I couldn't make it persist. Couldn't find anything in modinfo either. Perhaps there is a way to make CLI changes permanent that I am not aware of?

```
insmod corefreqk.ko Register_Governor=1 Register_CPU_Idle=1 Override_SubCstate="1,1,1,1,1,1,0,0"
```

1. _CoreFreq_ must controlled the idle states; thus parameter `Register_CPU_Idle=1`
  * See [CoreFreq as the Clock Source, CPU Freq and CPU Idle driver](https://github.com/cyring/CoreFreq/wiki/CoreFreq-as-the-Clock-Source,-CPU-Freq-and-CPU-Idle-driver)
2. In `Override_SubCstate` parameter, you set one per C-state, from `C1` to `C6`; remaining `C7`, `C8` set to zero
