### ISSUE TITLE
ArchLinux: "Remove DKMS modules" issue

### ISSUE THREAD

**Issue by cyring** [cyring/CoreFreq#508]
Issue raised in corefreq package [comments](https://aur.archlinux.org/pkgbase/corefreq)

https://github.com/cyring/CoreFreq/blob/85b1e626183986c3bdfcc9b2bb046e8f24a13882/dkms.conf#L26

This PKGBUILD [change](https://aur.archlinux.org/cgit/aur.git/commit/?h=corefreq&id=7a8c163499e8740bf6aa0b6d83f862c9712b8b25) is fixing the issue

**Comment by cyring** [comment]
[`dkms.conf`](https://github.com/cyring/CoreFreq/blob/master/dkms.conf) has been made for all distributions which use it.
Commenting the `POST_REMOVE` will impact all of them.
Need to do non-regression tests among all various packaging.

**Comment by inglor** [comment]
I maintain dkms.conf specifically for Archlinux but if you want to do that feel free. This is cause Archlinux use split packages for client/server/dkms.

**Comment by cyring** [comment]
> I maintain dkms.conf specifically for Archlinux but if you want to do that feel free. This is cause Archlinux use split packages for client/server/dkms.

OK, I'm fine with this.
Thanks.
