### ISSUE TITLE
Feature request: No background color

### ISSUE THREAD

**Issue by SairesArt** [cyring/CoreFreq#82]
Minor wish:
I'd love to have no background color (currently the gray) in the cli client of CoreFreq. I have looked through the help command and read the doc, but have found no option to disable the background color.

**Comment by cyring** [comment]
"No background color" is a difficult feature to program:
Space characters are part of cleaning drawing areas.
Removing color of spaces may lead to undefined results.
The CoreFreq UI is made with ASCII for Consoles.
A user theme with fixed background color is possible but it requires a long UI code refactoring.

**Comment by cyring** [comment]
A quick workaround is to modify the color palette of the terminal.
Alter the RGB of the background and the Black colors.
![2018-10-04-160244_527x280_scrot](https://user-images.githubusercontent.com/11563789/46479361-2d8b1180-c7ef-11e8-8c65-bbcf559c9418.png)
![2018-10-04-160238_600x471_scrot](https://user-images.githubusercontent.com/11563789/46479371-311e9880-c7ef-11e8-957a-74d25774e12c.png)
![2018-10-04-160158_642x386_scrot](https://user-images.githubusercontent.com/11563789/46479378-3380f280-c7ef-11e8-96c3-6d0da1a57d24.png)
![2018-10-04-160026_642x386_scrot](https://user-images.githubusercontent.com/11563789/46479383-35e34c80-c7ef-11e8-9ffd-fff751a0ed65.png)

**Comment by SairesArt** [comment]
Gah, I wanted my Distro's sexy Glass terminal shining through CoreFreq. Too bad, the terminal doesn't support custom colors.
Thank's for the suggestion though
![desktop](https://user-images.githubusercontent.com/10562480/46479834-447e3380-c7f0-11e8-8528-593aa37a137a.png)
![corefreq](https://user-images.githubusercontent.com/10562480/46480022-a048bc80-c7f0-11e8-9c36-62fc09ae8156.png)
