### ISSUE TITLE
Executing make does not enter kernel directory

### ISSUE THREAD

**Issue by wordlessly** [cyring/CoreFreq#86]
Also it does not create corefreqk.ko. See make output below:

> make
cc  -Wall -pthread -c corefreqd.c \
	-D FEAT_DBG=1 -o corefreqd.o
cc  -Wall -c corefreqm.c -o corefreqm.o
cc  -Wall corefreqd.c corefreqm.c \
	-D FEAT_DBG=1 -o corefreqd -lpthread -lm -lrt
cc  -Wall -c corefreq-cli.c -o corefreq-cli.o
cc  -Wall -c corefreq-ui.c -o corefreq-ui.o
cc  -Wall -c corefreq-cli-json.c \
	-o corefreq-cli-json.o
cc  -Wall -c corefreq-cli-extra.c \
	-o corefreq-cli-extra.o
cc  -Wall \
	corefreq-cli.c corefreq-ui.c \
	corefreq-cli-json.c corefreq-cli-extra.c \
	-o corefreq-cli -lm -lrt

**Comment by cyring** [comment]
Do you confirm you have installed the kernel headers/source ? 

Depending of your Linux distribution, if you install the dkms package, this may drag all the prerequisites for kernel module development.

**Comment by wordlessly** [comment]
I installed headers/source manually. Maybe you want to extend the description on how to make CoreFreq on Ubuntu.

Also add-apt-repository ppa:cyring/corefreq is empty. Maybe you want to remove the advice to add this repo to install CoreFreq.

Cheers!

**Comment by wordlessly** [comment]
Sorry, but I am not sure how to build the driver step by step. Can I tell make to do this?

Maybe I wasn't clear in my last message. I installed the headers/source for my kernel. After that the build did work flawlessly.

**Comment by cyring** [comment]
Ok I will soon release a new Makefile. Meanwhile the instructions I post above should build the missing `corefreqk.ko`

**Comment by cyring** [comment]
Please let me know if you can successfully build _CoreFreq_ ?

**Comment by cyring** [comment]
I'm closing the issue : a simple `Makefile` is released.
