### ISSUE TITLE
No temperature report on AMD Opteron

### ISSUE THREAD

**Issue by LexJackson** [cyring/CoreFreq#91]
First, this is fantastic software and exactly what I was looking for! Thank you for writing this! 

I read through the thread about no temperature report from Ryzen and suspect I have a similar issue.

With an insmod /var/lib/dkms/corefreqk/1.39/4.20.0-arch1-1-ARCH/x86_64/module/corefreqk.ko Experimental=1

Output of corefreq-cli -s is:

<img width="647" alt="screen shot 2019-01-10 at 10 58 18 am" src="https://user-images.githubusercontent.com/32887382/50980473-c902e100-14c6-11e9-8793-76d96564f80e.png">
<img width="645" alt="screen shot 2019-01-10 at 10 58 40 am" src="https://user-images.githubusercontent.com/32887382/50980476-cc966800-14c6-11e9-9610-eff33eabfbde.png">
<img width="646" alt="screen shot 2019-01-10 at 10 58 52 am" src="https://user-images.githubusercontent.com/32887382/50980480-cf915880-14c6-11e9-8398-7a64ce90355c.png">

I see no thermal data of course.

<img width="764" alt="screen shot 2019-01-10 at 10 47 04 am" src="https://user-images.githubusercontent.com/32887382/50980568-04051480-14c7-11e9-9395-4fec31b4b2f4.png">

The output of sensors does show the CPU Temps here:

<img width="472" alt="screen shot 2019-01-10 at 11 02 03 am" src="https://user-images.githubusercontent.com/32887382/50980641-34e54980-14c7-11e9-920a-37d0d214822e.png">

At your leisure, let me know what I should try. THANK YOU!

**Comment by LexJackson** [comment]
Thank you for the rapid reply!  

Here the output requested. 

<img width="1185" alt="screen shot 2019-01-10 at 1 34 23 pm" src="https://user-images.githubusercontent.com/32887382/50989148-9237c580-14dc-11e9-9900-1a7532300cdf.png">


Base clock i'm unsure about but the CPU's tend to clock pretty low when idle. Here's an output of cat /proc/cpuinfo | grep MHz.  They get pretty sleepy.

<img width="219" alt="screen shot 2019-01-10 at 1 36 38 pm" src="https://user-images.githubusercontent.com/32887382/50989223-c7441800-14dc-11e9-8867-eb7bb2d085a1.png">

**Comment by LexJackson** [comment]
Also adding, looks like detailed temp per core can be obtained. I'm using Turion Power Control to get this info. (tpc -temp). I believe it's using the cpuid kernel module for that info. 

![screen shot 2019-01-11 at 7 05 45 pm](https://user-images.githubusercontent.com/32887382/51065693-36e8fe80-15d4-11e9-8285-f303f0076208.png)

**Comment by cyring** [comment]
Hello,

For your testings, new code is available to read the processor temperature.

Remark: I presume there is only one sensor per package.

**Comment by LexJackson** [comment]
Thanks for the work! For some reason I'm not seeing any temp data now. 

I loaded corefreq with:
insmod /var/lib/dkms/corefreqk/1.39/4.20.0-arch1-1-ARCH/x86_64/module/corefreqk.ko Experimental=1
systemctl start corefreqd

Here's what I'm seeing (currently running an x265 encode btw)

![screen shot 2019-01-13 at 12 01 50 am](https://user-images.githubusercontent.com/32887382/51081814-d1c20580-16c6-11e9-8c0c-2749c69ec15f.png)

**Comment by cyring** [comment]
Can you try new code ?

You should also read `Bulldozer/Piledriver` as the architecture name.

**Comment by LexJackson** [comment]
Sorry, I thought I did, did a git clone on the repository and built it. I may have done something wrong. So sorry.

**Comment by cyring** [comment]
In the working directory, just `git pull` to get last source code then `make clean all` to rebuild

**Comment by LexJackson** [comment]
Will building from this PKGBUILD not pull the latest code?

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=corefreq-git

That's how I've been installing it.

**Comment by cyring** [comment]
The PKGBUILD may pull the latest and rebuild with`makepkg -sif`; however for our testing session, which implies many small changes, I recommend to clone the source code directly from the github then pull and rebuild whenever I notify a new push.

1. Uninstall, remove package dir
2. Clone from the GitHub and change to the cloned dir
3.  Force rebuild `make clean all`
4. Fully restart _CoreFreq_ , especially its driver corefreqk.ko

**Comment by cyring** [comment]
Using the latest code, please post screenshots of temperature b/c I need to know if the SMU queries are working? 
Thks

**Comment by LexJackson** [comment]
OK done. Still not seeing temperature data for some reason. Happy to keep testing, please let me know what I can do to help. THANK YOU!

![screen shot 2019-01-14 at 3 40 16 pm](https://user-images.githubusercontent.com/32887382/51139827-f0351780-1812-11e9-90e1-c103491c851b.png)

**Comment by LexJackson** [comment]
Here's the confirmation on the Experimental=1 flag and result. 

![screen shot 2019-01-15 at 2 35 43 pm](https://user-images.githubusercontent.com/32887382/51205030-ff7b9a00-18d2-11e9-8efd-c29e0dad369b.png)

![screen shot 2019-01-15 at 2 36 15 pm](https://user-images.githubusercontent.com/32887382/51205040-02768a80-18d3-11e9-9325-74d84412e23e.png)



I am compiling the new code now. Thanks!

**Comment by LexJackson** [comment]
[dmesgCoreFreqCapture.txt](https://github.com/cyring/CoreFreq/files/2761168/dmesgCoreFreqCapture.txt)

**Comment by cyring** [comment]
Can you replace and try with the following functions:

* corefreqk.c
```C
void Core_AMD_Family_15h_Temp(CORE *Core)
{
	TCTL_REGISTER TctlSensor = {0};

	RDPCI(TctlSensor, PCI_CONFIG_ADDRESS(0, 0x18, 0x3, 0xa4));
	Core->PowerThermal.Sensor = TctlSensor.CurTmp;

	if (Proc->Features.AdvPower.EDX.TTP == 1) {
		THERMTRIP_STATUS ThermTrip = {0};

		WRPCI(	SMU_AMD_THM_TRIP_REGISTER_F15H,
			SMU_AMD_INDEX_REGISTER_F15H);
		RDPCI(ThermTrip, SMU_AMD_DATA_REGISTER_F15H);

		Core->PowerThermal.Events = ThermTrip.SensorTrip << 0;
	}
}
```

* coretypes.h
```C
#define COMPUTE_THERMAL_AMD_15h(Temp, Param, Sensor)			\
	(Temp = (Sensor * 5 / 40) - 49)
```

**Comment by LexJackson** [comment]
Looks like it's showing something.. Not sure what. ;-)

<img width="1397" alt="screen shot 2019-01-15 at 10 18 07 pm" src="https://user-images.githubusercontent.com/32887382/51224374-82bce000-1913-11e9-84f5-51399a3783eb.png">

dmesg | grep Core 
[    0.969195] ACPI: Core revision 20181003
[    4.976436] systemd[1]: Listening on Process Core Dump Socket.
[ 9920.687007] CoreFreq(31:-1): Processor [ 6F_02] Architecture [Bulldozer/Piledriver] CPU [32/32]

**Comment by LexJackson** [comment]
Looks like that worked! What do I need to tweak to get all CPU's reporting? ;-) Thanks for your help!

<img width="1392" alt="screen shot 2019-01-16 at 8 54 56 am" src="https://user-images.githubusercontent.com/32887382/51253498-744ee280-196c-11e9-9485-1edb2a262d0b.png">

**Comment by cyring** [comment]
According to the datasheet, it is a sensor per socket.
To my understanding, no temperature per Core. 
But is your proc dual sockets, thus we could read two sensors.

Can you print the topology discovered by _CoreFreq_

`corefreq-cli -m`

**Comment by LexJackson** [comment]
I'm only seeing temp data for one of the 32 CPU's in that case shouldn't at least two temps be displayed since there are 2 CPU's?

<img width="625" alt="screen shot 2019-01-16 at 1 17 14 pm" src="https://user-images.githubusercontent.com/32887382/51269735-3ca66180-1991-11e9-98ad-0613ffbe1901.png">

**Comment by cyring** [comment]
So far only one sensor is queried (on the service thread; which is driven by the CPU wirh an enlightened number in the UI)

The remaining work consists in improving the AMD topology to make the difference between the two sockets: Node ID, Pkg, Module, Core and so on.
Then, set a CPU affinity of the service thread to the each socket. 
Finally collect the PCI sensor from the determined CPU.

**Comment by LexJackson** [comment]
Perfect, thank you very much for your help!

**Comment by cyring** [comment]
Btw do you know the size of the caches?
The L3 looks wrong. 
(due to a unit change between Zen and previous architectures)

**Comment by LexJackson** [comment]
Thanks for working on it!! Looking good so far. 

<img width="1396" alt="screen shot 2019-01-17 at 8 59 26 pm" src="https://user-images.githubusercontent.com/32887382/51360727-e02f6900-1a9a-11e9-8ac1-09ccfd6f0e96.png">

I'm able to see temps pretty well with tpc for now. Oh, and I have 4 CPU's now (as of yesterday)

<img width="592" alt="screen shot 2019-01-17 at 9 01 21 pm" src="https://user-images.githubusercontent.com/32887382/51360790-2389d780-1a9b-11e9-918d-4a37aefb3549.png">

**Comment by cyring** [comment]
Nice setup. 
64 CPU is so far the _CoreFreq_ limit.

What to understand from the Turion Power screenshot : the temperature granularity is at least per Node ?

**Comment by cyring** [comment]
Can you show the full topology with the 4 processors

**Comment by LexJackson** [comment]
Yes with the Turion screenshot I was simply showing that it's possible to see per node temp. How would you like me to show the topology? Happy to do it.

**Comment by cyring** [comment]
> Yes with the Turion screenshot I was simply showing that it's possible to see per node temp. How would you like me to show the topology? Happy to do it.

Just copy/past the output `corefreq-cli -m` with the Markdown code format

**Comment by LexJackson** [comment]
[corefreq-topology.log](https://github.com/cyring/CoreFreq/files/2774004/corefreq-topology.log)

**Comment by cyring** [comment]
I was expecting to read 16384 KB of L3 cache.
Can you modify the source as bellow at these lines: 
https://github.com/cyring/CoreFreq/blob/1554e89f4b77fe80bd7a50a3df51e97c4208fd2e/corefreqk.c#L1194

```C
	case AMD_Family_15h:
	  if ((Proc->Features.Std.EAX.ExtModel == 0x0)
	   && (Proc->Features.Std.EAX.Model >= 0x0)
	   && (Proc->Features.Std.EAX.Model <= 0xf))
	  {
		PROBE_FILTER_CTRL PF;
		RDPCI(PF, PCI_AMD_PROBE_FILTER_CTRL);
/*	    if (PF.Mode != 0b00) {*/
		/* Add to L3 the Sub Caches in 512 KB unit size.	*/
		Core->T.Cache[3].Size = Core->T.Cache[3].Size
		+ PF.SubCache0En ? (1 << (1 + (PF.SubCacheSize0 & 0b01))) : 0
		+ PF.SubCache1En ? (1 << (1 + (PF.SubCacheSize1 & 0b01))) : 0
		+ PF.SubCache2En ? (1 << (1 + (PF.SubCacheSize2 & 0b01))) : 0
		+ PF.SubCache3En ? (1 << (1 + (PF.SubCacheSize3 & 0b01))) : 0;
	    }
/*	  }*/
```

**Comment by cyring** [comment]
*Bump*

**Comment by LexJackson** [comment]
Thanks for the bump, so sorry, work and life! Looks like I did something wrong, I get build errors on the make clean all. 

Is this pasted in correctly?

`case AMD_Family_10h:
        case AMD_Family_11h:
        case AMD_Family_12h:
        case AMD_Family_14h:
        case AMD_Family_15h:
  if ((Proc->Features.Std.EAX.ExtModel == 0x0)
           && (Proc->Features.Std.EAX.Model >= 0x0)
           && (Proc->Features.Std.EAX.Model <= 0xf))
          {
                PROBE_FILTER_CTRL PF;
                RDPCI(PF, PCI_AMD_PROBE_FILTER_CTRL);
/*          if (PF.Mode != 0b00) {*/
                /* Add to L3 the Sub Caches in 512 KB unit size.        */
                Core->T.Cache[3].Size = Core->T.Cache[3].Size
                + PF.SubCache0En ? (1 << (1 + (PF.SubCacheSize0 & 0b01))) : 0
                + PF.SubCache1En ? (1 << (1 + (PF.SubCacheSize1 & 0b01))) : 0
                + PF.SubCache2En ? (1 << (1 + (PF.SubCacheSize2 & 0b01))) : 0
                + PF.SubCache3En ? (1 << (1 + (PF.SubCacheSize3 & 0b01))) : 0;
/*          }*/
          }
        case AMD_Family_16h:
                Core->T.ApicID    = leaf1_ebx.Init_APIC_ID;
                Core->T.CoreID    = leaf1_ebx.Init_APIC_ID;
                Core->T.PackageID = leaf1_ebx.Init_APIC_ID
                                  >> leaf80000008.ECX.ApicIdCoreIdSize;
                break;
        case AMD_Family_17h:`

**Comment by cyring** [comment]
New version pushed.
Please refresh source code then post:
* the topology `corefreq-cli -m` 
* the CPUID dump `corefreq-cli -u`

**Comment by LexJackson** [comment]
[CPUID-Dump.txt](https://github.com/cyring/CoreFreq/files/2793777/CPUID-Dump.txt)
[CoreFreq-m.txt](https://github.com/cyring/CoreFreq/files/2793779/CoreFreq-m.txt)

**Comment by cyring** [comment]
Hello,
This version 1.39.15 is focusing on the L3 Cache size. 
If your Piledriver processor is detected then any L3 Sub-Cache  has to be summed up to L3

**Comment by cyring** [comment]
The size of the L3 Cache in the Topology, please.

**Comment by LexJackson** [comment]
Hope this helps! Thanks!

[corefreq-cli-u.txt](https://github.com/cyring/CoreFreq/files/2805888/corefreq-cli-u.txt)
[corefreq-cli-m.txt](https://github.com/cyring/CoreFreq/files/2805889/corefreq-cli-m.txt)

**Comment by cyring** [comment]
Thanks for your return.

The Core ID topology looks better, but the L3 cache size remains at 12MB despite the PCI queries of the Sub-Caching data.

The next coding steps will consist in implementing the temperature sensor reading for each cores identified with an ID of # 0 . Thus four sensors (1 per package processor), if available in this architecture ?
```
CPU Pkg  Apic  Core Thread  Caches      (w)rite-Back (i)nclusive              
 #   ID   ID    ID     ID  L1-Inst Way  L1-Data Way      L2  Way      L3  Way 
00: BSP     0     0     -1      64  2        16  4      2048 16     12288 14  
01:   0     1     1     -1      64  2        16  4      2048 16     12288 14  
02:   0     2     2     -1      64  2        16  4      2048 16     12288 14  
...
15:   0    15    15     -1      64  2        16  4      2048 16     12288 14  
16:   1    32     0     -1      64  2        16  4      2048 16     12288 14  
17:   1    33     1     -1      64  2        16  4      2048 16     12288 14  
...
63:   3   111    15     -1      64  2        16  4      2048 16     12288 14  
```

**Comment by cyring** [comment]
Hello,
In the last code, you will get the temperature for each Core ID 0 (per Package) and the Voltage ID for any CPU.

I don't find a precise formula how to convert the VID to voltage, in Specs and this [AMD FX tuning guide](https://www.amd.com/Documents/AMD_FX_Performance_Tuning_Guide.pdf)

The same formula of the Zen architecture is copy-past to this function `COMPUTE_VOLTAGE_AMD_15h`
https://github.com/cyring/CoreFreq/blob/24bbcfe1dce4c580d8637b2bb7ef157154164788/coretypes.h#L284
You will get wrong voltage results but the VID should be correct. Feel free to modify the formula.

In the UI, please returns screenshots of the view "Power & Voltage".

The VID is specified to be per P-State, but you will have to experiment and determine if the VID is per Package, Node, or Core ?
For example, stress individually or group of Cores to observe how the VID differs.

**Comment by cyring** [comment]
Hello,
Any result from above request ?
Regards
CyrIng

**Comment by cyring** [comment]
I have done successful non-regression builds on several Linux (Arch, Ubuntu, Suse, CentOS)
You have to `git clone` from scratch again.

**Comment by cyring** [comment]
No code to edit. Everything has been back-ported; in last version 1.39.18, you should read the temperature and voltage ID for each processor.

**Comment by cyring** [comment]
Do you still have issues to build the latest version ?

**Comment by cyring** [comment]
Bump

**Comment by LexJackson** [comment]
Latest builds good. Thanks, here's the screen shot. Thanks!

<img width="1196" alt="screen shot 2019-02-07 at 8 08 02 pm" src="https://user-images.githubusercontent.com/32887382/52453175-2618a380-2b14-11e9-804c-3a6c5e2a9392.png">

**Comment by cyring** [comment]
Per CPU does not work. What is the specs voltage Vcore ? (BIOS)

About temperature, do you read distinct one per package processor ?

**Comment by cyring** [comment]
Hey, version 1.40 brings a new feature to stress a chosen CPU. See issue #97 
Based on the topology, you can stress a processor and check how its voltage VID differs from the others. 
Please let me know about the testing results b/c I don't if I'm on the good coding path with Opteron

**Comment by cyring** [comment]
Hello,
Just bumping my requests above 
Thank you

**Comment by cyring** [comment]
Any results of the voltage ?
