### ISSUE TITLE
Display a warning when trying to run corefreq-cli without having enabled corefreqd

### ISSUE THREAD

**Issue by pmav99** [cyring/CoreFreq#94]
Currently, when you start to run `corefreq-cli` without having started `corefreqd`, nothing is displayed on the screen. The only sign indicating that something went wrong is the return status. I think that displaying a message that the user should `modprobe corefreqk` and `systemctl start corefreqd.service` would be a nice addition from a UI point of view.

**Comment by cyring** [comment]
Indeed, I definitely need to make some UI and daemon improvements to display the reasons below.
(so far, the sole AUR [package](https://aur.archlinux.org/cgit/aur.git/plain/corefreq.install?h=corefreq-git) is showing the starting instructions)

* corefreqd

Code| Reason
-------|-----------
0|ok
1|command line syntax
2|insufficient root permissions
3|can not connect the driver

* corefreq-cli

Code| Reason
-------|-----------
0|ok
1|command line syntax
2| can not the daemon [opening shared memory]
3| can not the daemon [stating shared memory]
4| can not the daemon [mapping shared memory]

**Comment by cyring** [comment]
Last version, the Client now displays an error message when the daemon is unreachable, such as:
```
$ corefreq-cli 
Daemon connection error code 2
corefreq-shm: No such file or directory
```

**Comment by cyring** [comment]
Hello,
Do you have tested this enhancement ?

**Comment by pmav99** [comment]
Thank for the bump @cyring, I just did.
```
$ corefreq-cli
Daemon connection error code 2
corefreq-shm: No such file or directory

$ sudo modprobe corefreqk

$  corefreq-cli
Daemon connection error code 2
corefreq-shm: No such file or directory

$ sudo systemctl start corefreqd

$  corefreq-cli -k
Linux:                                                                          
|- Release                                                 [4.20.6-arch1-1-ARCH]
|- Version                         [#1 SMP PREEMPT Thu Jan 31 08:22:01 UTC 2019]
|- Machine                                                              [x86_64]
Memory:                                                                         
|- Total RAM                                                         16394648 KB
|- Shared RAM                                                          207224 KB
|- Free RAM                                                          12139928 KB
|- Buffer RAM                                                          247828 KB
|- Total High                                                               0 KB
|- Free High                                                                0 KB
Idle driver                                                        [@intel_idle]
   |- State:          POLL    C1      C1E     C3      C6      C7s     C10       
   |- Power:          -1      0       0       0       0       0       0         
   |- Latency:        0       2       10      70      85      124     890       
   |- Residency:      0       2       20      100     200     800     5000      
```

**Comment by pmav99** [comment]
For the daemon:
```
$ sudo systemctl stop corefreqd

$ sudo rmmod corefreqk

$ sudo systemctl start corefreqd

$ sudo systemctl status corefreqd
● corefreqd.service - CoreFreq Daemon
   Loaded: loaded (/usr/lib/systemd/system/corefreqd.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-02-07 10:16:38 EET; 3s ago
  Process: 1865 ExecStart=/bin/corefreqd -q (code=exited, status=3)
 Main PID: 1865 (code=exited, status=3)

Feb 07 10:16:38 laptopi systemd[1]: Started CoreFreq Daemon.
Feb 07 10:16:38 laptopi systemd[1]: corefreqd.service: Main process exited, code=exited, status=3/NOTIM>
Feb 07 10:16:38 laptopi systemd[1]: corefreqd.service: Failed with result 'exit-code'.
```

**Comment by cyring** [comment]
# Manual page generation
## Prerequisite
[help2man](https://www.archlinux.org/packages/extra/x86_64/help2man/)
## Generation
```
help2man -h '-h' -v '-v' -n corefreq-cli -s 1 -N -m corefreq-cli -o corefreq-cli.1 /bin/corefreq-cli
```
```
help2man -h '-h' --version-string '1.41' -n corefreqd -s 1 -N -m corefreqd -o corefreqd.1 ~/bin/corefreqd
```
## Issues and remainings
1. _Exit status:_ carriage returns are missing 
2. _Copyright_ is badly placed  
3. `corefreqd` must be completed with a '-v' argument  
4. must decide which manual section is appropriated  
5. `corefreqk.ko` needs a `manual` generator 

## Package installation
* help2man
  Has to be an optional dependency  
* ArchLinux  
  Where are generated the manuals ?  
  In a PKGBUILD function or `post_install()` in `corefreq.install`

**Comment by cyring** [comment]
Last _CoreFreq_ version, the Daemon and the Cli errors are being refactored:

CLASS | RC
----------|---
RC_SUCCESS | 0
RC_CMD_SYNTAX | 1
RC_SHM_FILE | 2
RC_SHM_MMAP | 3
RC_PERM_ERR | 4
RC_MEM_ERR | 5
RC_EXEC_ERR | 6
RC_SYS_CALL | 15

Contextually, the output will provide:
* app name
* description
* shm file name
* system code 
* source code line

## Examples
### Daemon
```
Driver connection error code 2
corefreq-shm: No such file or directory @ line 3810
```
```
corefreqd execution error code 13
Permission denied @ line 3995
```
### Cli
```
Daemon connection error code 2
corefreq-shm: No such file or directory @ line 7804
```

**Comment by cyring** [comment]
Error reports have been implemented > closing the issue.

Manuals will be produced later. 

Regards, 
CyrIng
