### ISSUE TITLE
Tools: stress a selected CPU

### ISSUE THREAD

**Issue by cyring** [cyring/CoreFreq#97]

**Comment by cyring** [comment]
This is the implementation of a feature requested by a user: trigger the Turbo frequency of a chosen CPU.

![2019-02-09-152556_724x484_scrot](https://user-images.githubusercontent.com/11563789/52521976-c808cf00-2c7f-11e9-9c24-86d8ebd0705e.png)
![2019-02-09-152628_724x484_scrot](https://user-images.githubusercontent.com/11563789/52521980-cccd8300-2c7f-11e9-9ccd-3442984b820b.png)

Please comment.

**Comment by StephanieSunshine** [comment]
Works great!  Is there a way to toggle it on and off from the command line?

**Comment by cyring** [comment]
Unfortunately no in the current code state.
The client passes those commands to the daemon through a ring protocol.

**Comment by cyring** [comment]
About the stress time duration: it is not defined in time units but in a number of loops passed as an argument in the function below.
https://github.com/cyring/CoreFreq/blob/fa57a81c160dd121f672618cf1a24146696e1e01/corefreqm.c#L123
However, the loops have been calibrated on my Xeon processor and I'm now in the reflexion of how to precisely convert a user specified duration in relation to the current processor base clock. Second step will consist in offering a list to choose securely among duration values.

**Comment by cyring** [comment]
Hello,

Version 1.41 : in the ` Slice counters [T] ` view is added the `Error` column which shows the CPUs calculus errors detected from the `Tools` algorithms.  
![2019-02-10-135647_886x580_scrot](https://user-images.githubusercontent.com/11563789/52535646-2f428400-2d51-11e9-87f4-0462a952bf46.png)
_Remark: the above screenshot presents fake errors for the testing purpose_  

![2019-02-10-160850_886x580_scrot](https://user-images.githubusercontent.com/11563789/52535728-2e5e2200-2d52-11e9-9d56-f935d32ae024.png)

_Remarks:_
_2. in nominal mode, no value is printed if no error is found_ 
_3. the error checking applies to Atomic operations, CRC result, and Conic calculus_ 


The CPU selector window has also be enhanced to present the topology information:
![2019-02-10-160759_886x580_scrot](https://user-images.githubusercontent.com/11563789/52535712-0d95cc80-2d52-11e9-9488-e1893880a399.png)

If you can not read the PMC0 counter and thus the Instructions elapsed, enter the following command as root
```
echo 2 > /sys/devices/cpu/rdpmc
```

Feel free to comment.
CyrIng

**Comment by cyring** [comment]
Display issue may happen in the below function when the ID equals -1
https://github.com/cyring/CoreFreq/blob/5dbc44a087f0a57511425014c46c6b12f8fb844d/corefreq-cli.c#L3478

Such as the Topology() function, fix with this format:
```C
		sprintf((char*) item, 	"   %02u  %4d%6d%6d   ",
					cpu,
					Shm->Cpu[cpu].Topology.PackageID,
					Shm->Cpu[cpu].Topology.CoreID,
					Shm->Cpu[cpu].Topology.ThreadID);
```

**Comment by cyring** [comment]
Closing the issue. 
In the future, I may add other cli commands.

**Comment by cyring** [comment]
Stress single Core with Ryzen 3700X does not reach Turbo.
Perhaps the same with Zen first generation and Zen+

Reopening this issue to collect users tests.

**Comment by adatum** [comment]
Turbo Select CPU for single cores is working fine for my Ryzen 2700X, reaching ~4.3-4.35 GHz. Tested on several cores.

**Comment by cyring** [comment]
> Turbo Select CPU for single cores is working fine for my Ryzen 2700X, reaching ~4.3-4.35 GHz. Tested on several cores.

Thank you.
I have remotely stressed a 3700X but could not trigger Turbo. Despite [here](https://github.com/cyring/CoreFreq/issues/133#issuecomment-511626249), it shows I can. Pretty confusing.

**Comment by cyring** [comment]
Closing this issue

**Comment by olejon** [comment]
> Stress single Core with Ryzen 3700X does not reach Turbo

Works fine on X570 + 3600X. Goes to almost 4.4 GHz as expected, also using Round Robin. Assume same results with 3rd Gen on X570. We'll see when I get my 3950X though.
